# Hello World Workflow
# Run: python run.py examples/hello_world/workflow.yaml

name: Hello World
description: A minimal example showing Flyto Core basics

steps:
  # Step 1: Reverse a string
  - id: reverse
    module: string.reverse
    params:
      text: "Hello Flyto"

  # Step 2: Convert to uppercase (using result from step 1)
  - id: shout
    module: string.uppercase
    params:
      text: "${reverse.result}"

# Expected output: "OTYFL OLLEH"
