#!/usr/bin/env python3
# Copyright 2026 Flyto2. Licensed under Apache-2.0. See LICENSE.

"""Render SECURITY_STATUS.md from security/advisories.json.

The status page is generated rather than written by hand for the same reason the
guard-coverage tests exist: a security claim that drifts from reality is worse
than no claim. Every row comes from the manifest, and
``tests/core/test_security_status.py`` asserts that each named regression test
actually resolves to a collectable test node — so the "Regression test" column
cannot quietly become fiction.

Usage:
    python scripts/generate_security_status.py           # write the file
    python scripts/generate_security_status.py --check   # fail if stale
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MANIFEST = ROOT / "security" / "advisories.json"
OUTPUT = ROOT / "SECURITY_STATUS.md"
PYPROJECT = ROOT / "pyproject.toml"

SEVERITY_ORDER = {"critical": 0, "high": 1, "medium": 2, "low": 3}
REPO_URL = "https://github.com/flytohub/flyto-core"


def load_advisories() -> list[dict]:
    return json.loads(MANIFEST.read_text(encoding="utf-8"))


def version_key(version: str) -> tuple:
    return tuple(int(part) for part in version.split(".") if part.isdigit())


def fully_patched_from(advisories: list[dict]) -> str:
    """The lowest version at which every published advisory is fixed.

    Deliberately distinct from the current release: they answer different
    questions ("what is the oldest version I can safely stay on" vs "what is
    the newest version"), and conflating them is how a status page starts
    telling readers something subtly untrue.
    """
    patched = {a["patched"].lstrip(">= ").strip() for a in advisories if a["patched"] != "-"}
    return max(patched, key=version_key)


def current_release() -> str:
    """The version this checkout ships, read from pyproject.toml."""
    for line in PYPROJECT.read_text(encoding="utf-8").splitlines():
        if line.startswith("version = "):
            return line.split("=", 1)[1].strip().strip('"')
    raise RuntimeError("could not read version from pyproject.toml")


def severity_counts(advisories: list[dict]) -> dict[str, int]:
    counts: dict[str, int] = {}
    for advisory in advisories:
        counts[advisory["severity"]] = counts.get(advisory["severity"], 0) + 1
    return counts


def test_link(reference: str) -> str:
    path, _, node = reference.partition("::")
    label = node or Path(path).name
    return f"[`{label}`]({path})"


def render(advisories: list[dict]) -> str:
    patched_from = fully_patched_from(advisories)
    release = current_release()
    counts = severity_counts(advisories)
    summary = ", ".join(
        f"{counts[sev]} {sev}"
        for sev in sorted(counts, key=lambda s: SEVERITY_ORDER.get(s, 9))
    )

    lines = [
        "<!-- Generated by scripts/generate_security_status.py; do not edit. -->",
        "",
        "# Security Status",
        "",
        f"**Current release: `{release}`.** Every advisory published against this "
        f"project is fixed as of `{patched_from}`, and every one has a named "
        "regression test that runs in CI.",
        "",
        f"Installing `>= {patched_from}` clears every known advisory; `{release}` "
        "is the supported line and the one that receives fixes. See "
        "[`SECURITY.md`](SECURITY.md#supported-versions).",
        "",
        f"{len(advisories)} advisories have been published and fixed "
        f"({summary}). They are listed here in full, oldest patch first, because "
        "the count is less informative than the pattern: almost all of them are "
        "two defects — a caller-supplied path reaching a filesystem sink, and a "
        "caller-supplied target reaching the network — found one module at a "
        "time.",
        "",
        "## How the recurrence was stopped",
        "",
        "Fixing these individually did not converge. The guards were centralized "
        "and correct; what was missing was any check that modules *called* them, "
        "so each wave closed the modules that had been reported and left the "
        "ones that had not.",
        "",
        "Both boundaries now have a registry-wide coverage test that fails the "
        "build rather than a convention that relies on reviewers:",
        "",
        "| Boundary | Enforced by | Coverage |",
        "| --- | --- | --- |",
        "| Filesystem | [`test_write_sink_coverage.py`](tests/core/test_write_sink_coverage.py) | Every registered path-shaped parameter must reach the sandbox guard or carry a verified non-filesystem exemption |",
        "| Outbound network | [`test_outbound_guard_coverage.py`](tests/core/test_outbound_guard_coverage.py) | Every registered URL/host-shaped parameter must reach an egress guard or carry a verified no-request/local-validation exemption |",
        "",
        "Exemptions must state what the parameter really addresses, and they are "
        "re-verified on every run: a module excused as \"makes no request\" fails "
        "the moment it opens a connection, and one excused for validating "
        "locally fails the moment that validation is removed.",
        "",
        "Applying those audits closed roughly 30 further modules that no "
        "advisory had named. See [`SECURITY.md`](SECURITY.md) for the "
        "environment variables that define both boundaries.",
        "",
        "## Published advisories",
        "",
        "| Advisory | Severity | Affected | Fixed in | Regression test |",
        "| --- | --- | --- | --- | --- |",
    ]

    ordered = sorted(
        advisories,
        key=lambda a: (a["published"], SEVERITY_ORDER.get(a["severity"], 9)),
    )
    for advisory in ordered:
        tests = " ".join(test_link(t) for t in advisory["regression_tests"])
        lines.append(
            f"| [{advisory['ghsa']}]({REPO_URL}/security/advisories/{advisory['ghsa']}) "
            f"| {advisory['severity']} "
            f"| `{advisory['affected']}` "
            f"| `{advisory['patched']}` "
            f"| {tests} |"
        )

    lines += [
        "",
        "## Reporting",
        "",
        "Private vulnerability reporting is enabled on this repository. See "
        "[`SECURITY.md`](SECURITY.md) for how to report and what to include.",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if the file is stale")
    args = parser.parse_args()

    rendered = render(load_advisories())

    if args.check:
        if not OUTPUT.exists():
            print(f"{OUTPUT.name} is missing; run scripts/generate_security_status.py")
            return 1
        if OUTPUT.read_text(encoding="utf-8") != rendered:
            print(f"{OUTPUT.name} is stale; run scripts/generate_security_status.py")
            return 1
        print(f"security status: PASS ({len(load_advisories())} advisories)")
        return 0

    OUTPUT.write_text(rendered, encoding="utf-8")
    print(f"security status: updated ({len(load_advisories())} advisories)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
