#!/usr/bin/env python3
"""Generate exhaustive Flyto2 Core references from implementation sources."""

from __future__ import annotations

import argparse
import ast
import json
import re
import sys
from collections import defaultdict
from pathlib import Path
from typing import Any, Iterable

import yaml

ROOT = Path(__file__).resolve().parents[1]
REFERENCE = ROOT / "docs" / "reference"
HEADER = "<!-- Generated by scripts/generate_reference.py; do not edit. -->\n\n"
HTTP_METHODS = {"get", "post", "put", "patch", "delete"}


def relative(path: Path) -> str:
    return path.relative_to(ROOT).as_posix()


def source_link(path: Path, line: int) -> str:
    rel = relative(path)
    return (
        f"[`{rel}:{line}`]"
        f"(https://github.com/flytohub/flyto-core/blob/main/{rel}#L{line})"
    )


def markdown_code(value: Any) -> str:
    return (
        str(value)
        .replace("|", "\\|")
        .replace("[", "&#91;")
        .replace("]", "&#93;")
        .replace("\n", " ")
    )


def clean(value: Any, limit: int = 240) -> str:
    text = " ".join(str(value or "").split())
    return text if len(text) <= limit else text[: limit - 3] + "..."


def parse(path: Path) -> ast.Module:
    return ast.parse(path.read_text(encoding="utf-8"), filename=str(path))


def literal(node: ast.AST | None, default: Any = "") -> Any:
    if node is None:
        return default
    try:
        return ast.literal_eval(node)
    except (TypeError, ValueError):
        try:
            return ast.unparse(node)
        except (AttributeError, ValueError):
            return default


def summary(node: ast.AST, fallback: str) -> str:
    doc = None
    if isinstance(
        node,
        (ast.Module, ast.ClassDef, ast.FunctionDef, ast.AsyncFunctionDef),
    ):
        doc = ast.get_docstring(node, clean=True)
    if not doc:
        return fallback
    return clean(re.split(r"(?<=[.!?])\s+|\n\s*\n", doc, maxsplit=1)[0])


def source_files() -> list[Path]:
    roots = [
        ROOT / "src",
        ROOT / "scripts",
        ROOT / "examples",
        ROOT / "plugin-template" / "src",
    ]
    files = [
        path
        for base in roots
        if base.exists()
        for path in base.rglob("*.py")
        if "tests" not in path.parts
    ]
    files.extend(
        path
        for path in (ROOT / "run.py", ROOT / "demo.py", ROOT / "demo" / "record-demo.py")
        if path.exists()
    )
    return sorted(set(files))


def callable_signature(node: ast.FunctionDef | ast.AsyncFunctionDef) -> str:
    prefix = "async def" if isinstance(node, ast.AsyncFunctionDef) else "def"
    returns = f" -> {ast.unparse(node.returns)}" if node.returns else ""
    return f"{prefix} {node.name}({ast.unparse(node.args)}){returns}"


def declarations(tree: ast.Module) -> list[tuple[int, str, str, str]]:
    rows: list[tuple[int, str, str, str]] = []

    def visit(nodes: Iterable[ast.stmt], owner: str = "") -> None:
        for node in nodes:
            if isinstance(node, ast.ClassDef):
                qualified = f"{owner}.{node.name}" if owner else node.name
                bases = ", ".join(ast.unparse(base) for base in node.bases)
                signature = f"class {qualified}({bases})" if bases else f"class {qualified}"
                rows.append(
                    (
                        node.lineno,
                        "class",
                        signature,
                        summary(node, f"Defines the {node.name} runtime contract."),
                    )
                )
                visit(node.body, qualified)
            elif isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                qualified = f"{owner}.{node.name}" if owner else node.name
                signature = callable_signature(node).replace(
                    f" {node.name}(", f" {qualified}(", 1
                )
                kind = "method" if owner else "function"
                rows.append(
                    (
                        node.lineno,
                        kind,
                        signature,
                        summary(node, f"Implements `{qualified}`; linked source is authoritative."),
                    )
                )
                visit(node.body, qualified)

    visit(tree.body)
    return sorted(rows)


def module_inventory() -> str:
    rows = []
    lines_total = 0
    declarations_total = 0
    for path in source_files():
        text = path.read_text(encoding="utf-8")
        tree = parse(path)
        count = len(declarations(tree))
        lines = len(text.splitlines())
        imports = sorted(
            {
                node.module.split(".")[0]
                for node in ast.walk(tree)
                if isinstance(node, ast.ImportFrom) and node.module
            }
            | {
                alias.name.split(".")[0]
                for node in ast.walk(tree)
                if isinstance(node, ast.Import)
                for alias in node.names
            }
        )
        rows.append((path, lines, count, ", ".join(imports[:12]) or "none", tree))
        lines_total += lines
        declarations_total += count

    out = [HEADER, "# Source Module Inventory\n\n"]
    out.append(
        f"Inventory: **{len(rows):,} Python files**, **{lines_total:,} lines**, and "
        f"**{declarations_total:,} class/function/method declarations**. Test files are "
        "covered by the test suite rather than treated as public implementation.\n\n"
    )
    out.append(
        "| Source module | Lines | Declarations | Import roots | Responsibility |\n"
        "|---|---:|---:|---|---|\n"
    )
    for path, lines, count, imports, tree in rows:
        purpose = summary(tree, "Implementation module; linked source is authoritative.")
        out.append(
            f"| {source_link(path, 1)} | {lines} | {count} | "
            f"`{markdown_code(imports)}` | {purpose} |\n"
        )
    return "".join(out)


def python_api() -> str:
    groups: dict[Path, list[tuple[int, str, str, str]]] = {}
    for path in source_files():
        rows = declarations(parse(path))
        if rows:
            groups[path] = rows
    total = sum(len(rows) for rows in groups.values())
    out = [HEADER, "# Python Declaration Reference\n\n"]
    out.append(
        "Every class, function, nested function, and method in maintained runtime, CLI, "
        f"script, example, and plugin-template sources: **{total:,} declarations across "
        f"{len(groups):,} files**.\n\n"
    )
    for path, rows in groups.items():
        out.append(
            f"## `{relative(path)}`\n\n"
            "| Kind | Signature | Responsibility | Source |\n"
            "|---|---|---|---|\n"
        )
        for line, kind, signature, purpose in rows:
            out.append(
                f"| {kind} | `{markdown_code(signature)}` | {purpose} | "
                f"{source_link(path, line)} |\n"
            )
        out.append("\n")
    return "".join(out)


def decorator_name(node: ast.AST) -> str:
    if isinstance(node, ast.Name):
        return node.id
    if isinstance(node, ast.Attribute):
        return f"{decorator_name(node.value)}.{node.attr}".strip(".")
    return ""


def registered_modules() -> str:
    rows = []
    for path in source_files():
        tree = parse(path)
        for node in ast.walk(tree):
            if not isinstance(node, (ast.ClassDef, ast.FunctionDef, ast.AsyncFunctionDef)):
                continue
            for decorator in node.decorator_list:
                if not isinstance(decorator, ast.Call):
                    continue
                if decorator_name(decorator.func).split(".")[-1] != "register_module":
                    continue
                metadata = {
                    item.arg: literal(item.value)
                    for item in decorator.keywords
                    if item.arg
                }
                module_id = metadata.get("module_id", "")
                if not isinstance(module_id, str) or not module_id:
                    continue
                rows.append(
                    (
                        module_id,
                        metadata.get("version", "1.0.0"),
                        metadata.get("category", ""),
                        node.name,
                        metadata.get("requires_credentials", False),
                        metadata.get("required_permissions", []),
                        path,
                        node.lineno,
                    )
                )
    rows.sort()
    out = [HEADER, "# Registered Module Source Map\n\n"]
    out.append(
        f"The AST contains **{len(rows)} explicit, literal `@register_module` declarations**. "
        "This static count can exceed the public runtime catalog because discovery, "
        "compatibility aliases, dependency availability, and policy gates select the active "
        "set. Runtime-discovered totals and every parameter/output contract remain in "
        "[Tool Catalog](../TOOL_CATALOG.md); this map proves implementation ownership.\n\n"
    )
    out.append(
        "| Module ID | Version | Category | Callable | Credentials | Permissions | Source |\n"
        "|---|---|---|---|---|---|---|\n"
    )
    for module_id, version, category, name, credentials, permissions, path, line in rows:
        out.append(
            f"| `{module_id}` | `{version}` | `{category}` | `{name}` | "
            f"{'yes' if credentials else 'no'} | `{markdown_code(permissions)}` | "
            f"{source_link(path, line)} |\n"
        )
    return "".join(out)


def cli_reference() -> str:
    rows: list[dict[str, Any]] = []
    parser_vars: dict[tuple[Path, str], str] = {}
    arguments: dict[tuple[Path, str], list[dict[str, Any]]] = defaultdict(list)
    cli_files = sorted((ROOT / "src" / "cli").glob("*.py"))

    for path in cli_files:
        tree = parse(path)
        events = [
            node
            for node in ast.walk(tree)
            if isinstance(node, (ast.Assign, ast.Expr, ast.Call))
        ]
        events.sort(key=lambda node: (node.lineno, node.col_offset))
        for node in events:
            variable = ""
            if isinstance(node, ast.Assign) and isinstance(node.value, ast.Call):
                call = node.value
                variable = next(
                    (target.id for target in node.targets if isinstance(target, ast.Name)),
                    "",
                )
            elif isinstance(node, ast.Expr) and isinstance(node.value, ast.Call):
                call = node.value
            elif isinstance(node, ast.Call):
                if not isinstance(node.func, ast.Attribute):
                    continue
                if node.func.attr != "add_argument" or not isinstance(
                    node.func.value, ast.Name
                ):
                    continue
                command = parser_vars.get((path, node.func.value.id))
                if not command:
                    continue
                keywords = {
                    item.arg: literal(item.value) for item in node.keywords if item.arg
                }
                flags = [literal(item) for item in node.args]
                nargs = keywords.get("nargs", "")
                positional = bool(flags) and isinstance(flags[0], str) and not flags[0].startswith("-")
                required = bool(keywords.get("required", False)) or (
                    positional and nargs not in {"?", "*", "argparse.REMAINDER"}
                )
                arguments[(path, command)].append(
                    {
                        "flags": ", ".join(map(str, flags)),
                        "required": required,
                        "default": keywords.get("default", ""),
                        "choices": keywords.get("choices", ""),
                        "help": keywords.get("help", ""),
                        "line": node.lineno,
                    }
                )
                continue
            else:
                continue
            if not isinstance(call.func, ast.Attribute) or call.func.attr != "add_parser":
                continue
            if not call.args:
                continue
            name = literal(call.args[0])
            if not isinstance(name, str):
                continue
            keywords = {item.arg: literal(item.value) for item in call.keywords if item.arg}
            owner = path.stem if path.stem in {"plugin", "template"} else ""
            command = (
                f"flyto {owner} {name}"
                if owner and name != owner
                else f"flyto {name}"
            )
            if variable:
                parser_vars[(path, variable)] = command
            rows.append(
                {
                    "path": path,
                    "line": node.lineno,
                    "command": command,
                    "variable": variable,
                    "description": keywords.get("description") or keywords.get("help") or "",
                }
            )

    rows.sort(key=lambda item: item["command"])
    out = [HEADER, "# CLI Parser Reference\n\n"]
    out.append(
        f"The implementation defines **{len(rows)} parser commands** and "
        f"**{sum(len(items) for items in arguments.values())} arguments**. Recipe-specific "
        "arguments are generated from recipe parameter schemas at runtime and documented in "
        "[Recipes](../RECIPES.md).\n\n"
    )
    for row in rows:
        out.append(f"## `{row['command']}`\n\n{clean(row['description'])}\n\n")
        out.append(f"Parser source: {source_link(row['path'], row['line'])}.\n\n")
        items = arguments[(row["path"], row["command"])]
        if not items:
            out.append("This command has no static command-specific arguments.\n\n")
            continue
        out.append(
            "| Argument | Required | Default | Choices | Purpose | Source |\n"
            "|---|---|---|---|---|---|\n"
        )
        for item in items:
            choices = item["choices"]
            if isinstance(choices, (list, tuple)):
                choices = ", ".join(map(str, choices))
            out.append(
                f"| `{markdown_code(item['flags'])}` | "
                f"{'yes' if item['required'] else 'no'} | "
                f"`{markdown_code(item['default'])}` | `{markdown_code(choices)}` | "
                f"{clean(item['help'])} | {source_link(row['path'], item['line'])} |\n"
            )
        out.append("\n")
    return "".join(out)


def http_reference() -> str:
    rows = []
    for path in source_files():
        tree = parse(path)
        for node in ast.walk(tree):
            if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                continue
            for decorator in node.decorator_list:
                if not isinstance(decorator, ast.Call) or not isinstance(decorator.func, ast.Attribute):
                    continue
                method = decorator.func.attr.lower()
                if method not in HTTP_METHODS or not decorator.args:
                    continue
                route = literal(decorator.args[0])
                if not isinstance(route, str):
                    continue
                rel = relative(path)
                if rel.startswith("src/core/api/routes/"):
                    prefix = "/mcp" if path.stem == "mcp" else "/v1"
                    mounted = "Execution API"
                elif rel == "src/core/api/server.py":
                    prefix = ""
                    mounted = "Execution API"
                elif rel == "src/core/verification_service.py":
                    prefix = ""
                    mounted = "verification service"
                elif rel == "src/core/api/plugins/routes.py":
                    prefix = "/api/v1/plugins"
                    mounted = "router factory; not mounted by create_app"
                else:
                    continue
                full_path = prefix.rstrip("/") + "/" + route.lstrip("/")
                if full_path != "/":
                    full_path = full_path.rstrip("/")
                keywords = {item.arg: ast.unparse(item.value) for item in decorator.keywords if item.arg}
                dependencies = keywords.get("dependencies", "")
                signature_dependencies = ast.unparse(node.args)
                if "require_run_auth" in dependencies or "require_run_auth" in signature_dependencies:
                    auth = "internal key"
                elif "require_auth" in dependencies or "require_auth" in signature_dependencies:
                    auth = "bearer token"
                else:
                    auth = "none"
                rows.append(
                    (method.upper(), full_path, node.name, auth, mounted, path, node.lineno, node)
                )
    rows.sort(key=lambda item: (item[1], item[0], relative(item[5])))
    out = [HEADER, "# HTTP Route Reference\n\n"]
    out.append(
        f"Static FastAPI decorators define **{len(rows)} operations**. Mount status is explicit: "
        "a router factory is not a deployed endpoint until `create_app` includes it.\n\n"
    )
    out.append(
        "| Method | Path | Handler | Auth dependency | Runtime surface | Purpose | Source |\n"
        "|---|---|---|---|---|---|---|\n"
    )
    for method, route, handler, auth, mounted, path, line, node in rows:
        out.append(
            f"| `{method}` | `{route}` | `{handler}` | {auth} | "
            f"{mounted} | {summary(node, 'HTTP operation; linked handler is authoritative.')} | "
            f"{source_link(path, line)} |\n"
        )
    return "".join(out)


def configuration_reference() -> str:
    env: dict[str, set[tuple[Path, int]]] = defaultdict(set)
    patterns = (
        re.compile(r"os\.environ\.get\([\"']([A-Z][A-Z0-9_]+)"),
        re.compile(r"os\.getenv\([\"']([A-Z][A-Z0-9_]+)"),
        re.compile(r"os\.environ\[[\"']([A-Z][A-Z0-9_]+)"),
    )
    for path in source_files():
        lines = path.read_text(encoding="utf-8").splitlines()
        for line_number, line in enumerate(lines, start=1):
            for pattern in patterns:
                for match in pattern.finditer(line):
                    env[match.group(1)].add((path, line_number))

    recipe_files = sorted((ROOT / "src" / "recipes").glob("*.yaml"))
    workflow_files = sorted((ROOT / "workflows").rglob("*.yaml"))
    bundle_files = sorted((ROOT / "src" / "recipe_bundles").glob("*.yaml"))
    out = [HEADER, "# Configuration And Packaged Assets\n\n"]
    out.append(
        f"Implementation sources read **{len(env)} environment-variable names**. The package "
        f"ships **{len(recipe_files)} recipes** and **{len(bundle_files)} recipe bundles**; the "
        f"repository also maintains **{len(workflow_files)} workflow fixtures/templates**.\n\n"
    )
    out.append("## Environment variables\n\n| Variable | Readers |\n|---|---|\n")
    for name, readers in sorted(env.items()):
        links = ", ".join(source_link(path, line) for path, line in sorted(readers))
        out.append(f"| `{name}` | {links} |\n")
    for heading, files in (
        ("Packaged recipes", recipe_files),
        ("Packaged recipe bundles", bundle_files),
        ("Maintained workflow files", workflow_files),
    ):
        out.append(f"\n## {heading}\n\n| Asset | Name | Steps |\n|---|---|---:|\n")
        for path in files:
            data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
            name = data.get("name") or data.get("id") or path.stem
            steps = data.get("steps", [])
            out.append(
                f"| {source_link(path, 1)} | {clean(name)} | "
                f"{len(steps) if isinstance(steps, list) else 0} |\n"
            )
    return "".join(out)


def recipe_reference() -> str:
    recipe_files = sorted((ROOT / "src" / "recipes").glob("*.yaml"))
    out = [HEADER, "# Packaged Recipe Reference\n\n"]
    out.append(
        f"The package ships **{len(recipe_files)} executable recipes**. Each row is generated "
        "from the YAML asset so parameters, step IDs, and module composition cannot drift "
        "from the implementation. Use `flyto recipe <name> --help` for runtime argument "
        "rendering.\n\n"
    )
    out.append(
        "| Recipe | Purpose | Parameters | Steps | Modules | Source |\n"
        "|---|---|---|---:|---|---|\n"
    )
    for path in recipe_files:
        data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
        raw_args = data.get("args", {})
        params = []
        if isinstance(raw_args, dict):
            for name, details in raw_args.items():
                details = details if isinstance(details, dict) else {}
                marker = " required" if details.get("required") else ""
                default = details.get("default")
                default_text = f"={default}" if default is not None else ""
                params.append(f"{name}{default_text}{marker}")
        steps = data.get("steps", [])
        steps = steps if isinstance(steps, list) else []
        modules = [
            str(step.get("module"))
            for step in steps
            if isinstance(step, dict) and step.get("module")
        ]
        out.append(
            f"| `{path.stem}` | {clean(data.get('description') or data.get('name') or '')} | "
            f"`{markdown_code(', '.join(params) or 'none')}` | {len(steps)} | "
            f"`{markdown_code(', '.join(modules) or 'none')}` | {source_link(path, 1)} |\n"
        )
    return "".join(out)


def reference_index() -> str:
    return HEADER + """# Generated Reference

- [Source module inventory](source-modules.md): every maintained Python file, size, imports, purpose, and declaration count.
- [Python declaration reference](python-api.md): every class, function, nested function, and method signature.
- [Registered module source map](registered-modules.md): every static `@register_module` declaration and implementation link.
- [CLI parser reference](cli.md): every static CLI parser command and argument.
- [HTTP route reference](http-api.md): every FastAPI route with mount and decorator-auth status.
- [Configuration and packaged assets](configuration.md): environment readers, recipes, bundles, and workflow files.
- [Packaged recipe reference](recipes.md): every recipe parameter and composed module step.
- [Runtime Tool Catalog](../TOOL_CATALOG.md): all registry-discovered modules with parameter and output schemas.

Run `.venv/bin/python scripts/generate_reference.py` after changing documented
source. CI runs the same command with `--check` and rejects drift.
"""


def outputs() -> dict[Path, str]:
    documents = {
        REFERENCE / "README.md": reference_index(),
        REFERENCE / "source-modules.md": module_inventory(),
        REFERENCE / "python-api.md": python_api(),
        REFERENCE / "registered-modules.md": registered_modules(),
        REFERENCE / "cli.md": cli_reference(),
        REFERENCE / "http-api.md": http_reference(),
        REFERENCE / "configuration.md": configuration_reference(),
        REFERENCE / "recipes.md": recipe_reference(),
    }
    return {path: content.rstrip() + "\n" for path, content in documents.items()}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail when output is stale")
    args = parser.parse_args()
    stale = []
    for path, content in outputs().items():
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                stale.append(relative(path))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
    if stale:
        print(
            "stale generated documentation:\n" + "\n".join(f"- {item}" for item in stale),
            file=sys.stderr,
        )
        return 1
    counts = {
        "source_files": len(source_files()),
        "declarations": sum(len(declarations(parse(path))) for path in source_files()),
    }
    print(
        ("generated documentation: PASS " if args.check else "generated documentation: updated ")
        + json.dumps(counts, sort_keys=True)
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
