#!/usr/bin/env python3
# Copyright 2026 Flyto2. Licensed under Apache-2.0. See LICENSE.

"""Render SECURITY_STATUS.md from security/advisories.json.

The status page is generated rather than written by hand for the same reason the
guard-coverage tests exist: a security claim that drifts from reality is worse
than no claim. Every row comes from the manifest, and
``tests/core/test_security_status.py`` asserts that each named regression test
actually resolves to a collectable test node — so the "Regression test" column
cannot quietly become fiction.

Usage:
    python scripts/generate_security_status.py           # write the file
    python scripts/generate_security_status.py --check   # fail if stale
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MANIFEST = ROOT / "security" / "advisories.json"
OUTPUT = ROOT / "SECURITY_STATUS.md"

SEVERITY_ORDER = {"critical": 0, "high": 1, "medium": 2, "low": 3}
REPO_URL = "https://github.com/flytohub/flyto-core"


def load_advisories() -> list[dict]:
    return json.loads(MANIFEST.read_text(encoding="utf-8"))


def current_secure_release(advisories: list[dict]) -> str:
    """The highest patched version across all advisories."""

    def key(version: str) -> tuple:
        return tuple(int(part) for part in version.split(".") if part.isdigit())

    patched = {a["patched"].lstrip(">= ").strip() for a in advisories if a["patched"] != "-"}
    return max(patched, key=key)


def severity_counts(advisories: list[dict]) -> dict[str, int]:
    counts: dict[str, int] = {}
    for advisory in advisories:
        counts[advisory["severity"]] = counts.get(advisory["severity"], 0) + 1
    return counts


def test_link(reference: str) -> str:
    path, _, node = reference.partition("::")
    label = node or Path(path).name
    return f"[`{label}`]({path})"


def render(advisories: list[dict]) -> str:
    secure = current_secure_release(advisories)
    counts = severity_counts(advisories)
    summary = ", ".join(
        f"{counts[sev]} {sev}"
        for sev in sorted(counts, key=lambda s: SEVERITY_ORDER.get(s, 9))
    )

    lines = [
        "<!-- Generated by scripts/generate_security_status.py; do not edit. -->",
        "",
        "# Security Status",
        "",
        f"**Current secure release: `{secure}`.** Every advisory published against "
        "this project is patched at or below that version, and every one has a "
        "named regression test that runs in CI.",
        "",
        f"{len(advisories)} advisories have been published and fixed "
        f"({summary}). They are listed here in full, oldest patch first, because "
        "the count is less informative than the pattern: almost all of them are "
        "two defects — a caller-supplied path reaching a filesystem sink, and a "
        "caller-supplied target reaching the network — found one module at a "
        "time.",
        "",
        "## How the recurrence was stopped",
        "",
        "Fixing these individually did not converge. The guards were centralized "
        "and correct; what was missing was any check that modules *called* them, "
        "so each wave closed the modules that had been reported and left the "
        "ones that had not.",
        "",
        "Both boundaries now have a registry-wide coverage test that fails the "
        "build rather than a convention that relies on reviewers:",
        "",
        "| Boundary | Enforced by | Coverage |",
        "| --- | --- | --- |",
        "| Filesystem | [`test_write_sink_coverage.py`](tests/core/test_write_sink_coverage.py) | 88 modules declare a path parameter: 71 reach the guard, 17 are documented as not filesystem paths, 0 unaccounted |",
        "| Outbound network | [`test_outbound_guard_coverage.py`](tests/core/test_outbound_guard_coverage.py) | 57 modules declare a URL/host parameter: 46 reach a guard, 11 are documented as never reaching the network, 0 unaccounted |",
        "",
        "Exemptions must state what the parameter really addresses, and they are "
        "re-verified on every run: a module excused as \"makes no request\" fails "
        "the moment it opens a connection, and one excused for validating "
        "locally fails the moment that validation is removed.",
        "",
        "Applying those audits closed roughly 30 further modules that no "
        "advisory had named. See [`SECURITY.md`](SECURITY.md) for the "
        "environment variables that define both boundaries.",
        "",
        "## Published advisories",
        "",
        "| Advisory | Severity | Affected | Fixed in | Regression test |",
        "| --- | --- | --- | --- | --- |",
    ]

    ordered = sorted(
        advisories,
        key=lambda a: (a["published"], SEVERITY_ORDER.get(a["severity"], 9)),
    )
    for advisory in ordered:
        tests = " ".join(test_link(t) for t in advisory["regression_tests"])
        lines.append(
            f"| [{advisory['ghsa']}]({REPO_URL}/security/advisories/{advisory['ghsa']}) "
            f"| {advisory['severity']} "
            f"| `{advisory['affected']}` "
            f"| `{advisory['patched']}` "
            f"| {tests} |"
        )

    lines += [
        "",
        "## Reporting",
        "",
        "Private vulnerability reporting is enabled on this repository. See "
        "[`SECURITY.md`](SECURITY.md) for how to report and what to include.",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if the file is stale")
    args = parser.parse_args()

    rendered = render(load_advisories())

    if args.check:
        if not OUTPUT.exists():
            print(f"{OUTPUT.name} is missing; run scripts/generate_security_status.py")
            return 1
        if OUTPUT.read_text(encoding="utf-8") != rendered:
            print(f"{OUTPUT.name} is stale; run scripts/generate_security_status.py")
            return 1
        print(f"security status: PASS ({len(load_advisories())} advisories)")
        return 0

    OUTPUT.write_text(rendered, encoding="utf-8")
    print(f"security status: updated ({len(load_advisories())} advisories)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
