#!/usr/bin/env bash
set -euo pipefail

# ==============================================================================
# verify-robotics-registration.sh
#
# Strict, local, NON-ACTUATING Core-side verifier for one already-finished
# flyto-modules-robotics Gazebo evidence run.
#
# What this script proves:
#
#   1. One finished flyto-modules-robotics Gazebo evidence run is internally
#      consistent, fresh, hash-intact, and carries the contract versions, pass
#      facts, restoration facts, zero-command facts and final-status facts its
#      own contracts promise.
#   2. The flyto-modules-robotics source in the derived repository builds
#      exactly one wheel, and that wheel - installed offline into a throwaway
#      target - registers into *this* flyto-core checkout through the real
#      public ModuleRegistry plugin surface as the `robotics` entry point.
#   3. The three robotics modules produce declaration-only plans: nothing is
#      dispatched, every plan satisfies flyto.robotics.plan.v1 and ends in
#      `safe_stop`, and every plan is bound to a synthetic device id that
#      exists only inside this verification.
#
# What this script does NOT prove and does NOT do:
#
#   * It is NOT physical-hardware evidence. Every physical fact it reports is
#     restated from a Gazebo simulation run that happened earlier, elsewhere.
#   * It never contacts hardware, never starts ROS / Gazebo / Lima, never
#     connects a socket, never logs in, never dispatches a plan, and never
#     publishes cmd_vel. The embedded verifier disables subprocess execution
#     and outbound networking inside its own interpreter, so "non-actuating"
#     is enforced rather than merely asserted.
#   * It never mutates the flyto-modules-robotics or flyto-robotics
#     repositories. The wheel is built from a scratch copy of the source tree,
#     and evidence files are only ever read.
#
# Usage:
#   scripts/verify-robotics-registration.sh <run-dir>
#   scripts/verify-robotics-registration.sh --run-dir <run-dir>
#   FLYTO_ROBOTICS_RUN_DIR=<run-dir> scripts/verify-robotics-registration.sh
#
# <run-dir> may also be the canonical run parent directory
# (<modules-repo>/results/modules-robotics-gazebo) or the modules repository
# root, but only when that location holds exactly one non-symlink run.
#
# Environment:
#   FLYTO_ROBOTICS_RUN_DIR        Run directory (lowest-precedence input).
#   FLYTO_VERIFY_PYTHON           Interpreter used to build, install and
#                                 verify. Defaults to python3. Must be 3.9+.
#   FLYTO_VERIFY_MAX_AGE_SECONDS  Explicit maximum evidence age in seconds.
#                                 Default 7200, hard upper bound 86400.
#
# Options:
#   --run-dir <dir>          Evidence run directory.
#   --max-age-seconds <n>    Explicit maximum evidence age (1..86400).
#   -h, --help               Show this help.
#
# Exit status is 0 only when every invariant holds.
# ==============================================================================

DEFAULT_MAX_AGE_SECONDS=7200
HARD_MAX_AGE_SECONDS=86400
RUN_PARENT_NAME="modules-robotics-gazebo"
SCRATCH_PREFIX="flyto-robotics-verify"
readonly DEFAULT_MAX_AGE_SECONDS HARD_MAX_AGE_SECONDS RUN_PARENT_NAME SCRATCH_PREFIX

PROG="$(basename -- "$0")"

die() {
    printf '%s: error: %s\n' "$PROG" "$*" >&2
    exit 1
}

note() {
    printf '%s: %s\n' "$PROG" "$*" >&2
}

usage() {
    sed -n '4,60p' "$0" | sed -e 's/^#\{1,\} \{0,1\}//' -e 's/^#$//'
}

# ------------------------------------------------------------------------------
# Path hygiene
#
# Every path handed to the embedded verifier is embedded in a JSON config file
# generated by shell printf. Rather than build a general JSON escaper in bash
# 3.2, refuse the small set of characters that would make escaping necessary. A
# verification run is allowed to be picky about where it is asked to look.
# ------------------------------------------------------------------------------
assert_plain_path() {
    local label="$1" value="$2"
    case "$value" in
        '')     die "$label is empty" ;;
        *'"'*)  die "$label contains a double quote, which this verifier refuses: $value" ;;
        *'\'*)  die "$label contains a backslash, which this verifier refuses: $value" ;;
        *'$'*)  die "$label contains a dollar sign, which this verifier refuses: $value" ;;
        *'`'*)  die "$label contains a backtick, which this verifier refuses: $value" ;;
    esac
    case "$value" in
        /*) : ;;
        *)  die "$label is not absolute: $value" ;;
    esac
    if printf '%s' "$value" | LC_ALL=C tr -d '[:print:]' | LC_ALL=C grep -q .; then
        die "$label contains control characters, which this verifier refuses"
    fi
}

# Physical, symlink-free absolute path of an existing directory.
canonical_dir() {
    local d="$1"
    [ -d "$d" ] || die "not a directory: $d"
    (cd -P -- "$d" >/dev/null 2>&1 && pwd -P) || die "cannot canonicalise directory: $d"
}

# ------------------------------------------------------------------------------
# Argument parsing
# ------------------------------------------------------------------------------
RUN_DIR_ARG=""
MAX_AGE_ARG=""
MAX_AGE_SOURCE="default"

while [ "$#" -gt 0 ]; do
    case "$1" in
        -h|--help)
            usage
            exit 0
            ;;
        --run-dir)
            [ "$#" -ge 2 ] || die "--run-dir requires a value"
            [ -z "$RUN_DIR_ARG" ] || die "run directory given more than once"
            RUN_DIR_ARG="$2"
            shift 2
            ;;
        --run-dir=*)
            [ -z "$RUN_DIR_ARG" ] || die "run directory given more than once"
            RUN_DIR_ARG="${1#--run-dir=}"
            shift
            ;;
        --max-age-seconds)
            [ "$#" -ge 2 ] || die "--max-age-seconds requires a value"
            MAX_AGE_ARG="$2"
            MAX_AGE_SOURCE="--max-age-seconds"
            shift 2
            ;;
        --max-age-seconds=*)
            MAX_AGE_ARG="${1#--max-age-seconds=}"
            MAX_AGE_SOURCE="--max-age-seconds"
            shift
            ;;
        --)
            shift
            ;;
        -*)
            die "unknown option: $1 (try --help)"
            ;;
        *)
            [ -z "$RUN_DIR_ARG" ] || die "exactly one run directory may be given; got a second: $1"
            RUN_DIR_ARG="$1"
            shift
            ;;
    esac
done

if [ -z "$RUN_DIR_ARG" ]; then
    RUN_DIR_ARG="${FLYTO_ROBOTICS_RUN_DIR:-}"
    [ -n "$RUN_DIR_ARG" ] \
        || die "no run directory given (positional, --run-dir, or FLYTO_ROBOTICS_RUN_DIR); try --help"
fi

if [ -z "$MAX_AGE_ARG" ] && [ -n "${FLYTO_VERIFY_MAX_AGE_SECONDS:-}" ]; then
    MAX_AGE_ARG="$FLYTO_VERIFY_MAX_AGE_SECONDS"
    MAX_AGE_SOURCE="FLYTO_VERIFY_MAX_AGE_SECONDS"
fi

if [ -n "$MAX_AGE_ARG" ]; then
    case "$MAX_AGE_ARG" in
        ''|*[!0-9]*) die "maximum evidence age must be a positive integer number of seconds, got: $MAX_AGE_ARG" ;;
    esac
    MAX_AGE_SECONDS=$((10#$MAX_AGE_ARG))
    [ "$MAX_AGE_SECONDS" -ge 1 ] \
        || die "maximum evidence age must be at least 1 second"
    [ "$MAX_AGE_SECONDS" -le "$HARD_MAX_AGE_SECONDS" ] \
        || die "maximum evidence age $MAX_AGE_SECONDS exceeds the hard bound of $HARD_MAX_AGE_SECONDS seconds"
else
    MAX_AGE_SECONDS="$DEFAULT_MAX_AGE_SECONDS"
fi

# ------------------------------------------------------------------------------
# Locate this Core checkout
# ------------------------------------------------------------------------------
SCRIPT_DIR="$(canonical_dir "$(dirname -- "$0")")"
CORE_ROOT="$(canonical_dir "$SCRIPT_DIR/..")"
CORE_SRC="$CORE_ROOT/src"
[ -d "$CORE_SRC/core" ] || die "this does not look like a flyto-core checkout (missing $CORE_SRC/core)"
[ -f "$CORE_ROOT/pyproject.toml" ] || die "this does not look like a flyto-core checkout (missing pyproject.toml)"
assert_plain_path "core root" "$CORE_ROOT"

# ------------------------------------------------------------------------------
# Resolve the run directory
#
# A run directory is identified by the three artifacts the upper closure always
# writes. A parent directory or repository root is accepted only when it
# resolves, unambiguously, to exactly one non-symlink run.
# ------------------------------------------------------------------------------
looks_like_run_dir() {
    [ -f "$1/report.json" ] && [ -f "$1/cleanup.json" ] && [ -f "$1/lower-evidence.json" ]
}

sole_run_in_parent() {
    local parent="$1"
    local candidate="" entry="" count=0 had_nullglob=0
    if shopt -q nullglob; then had_nullglob=1; else shopt -s nullglob; fi
    for entry in "$parent"/*; do
        [ -d "$entry" ] || continue
        if [ -L "$entry" ]; then
            note "ignoring symlinked entry while resolving the sole run: $entry"
            continue
        fi
        looks_like_run_dir "$entry" || continue
        candidate="$entry"
        count=$((count + 1))
    done
    [ "$had_nullglob" -eq 1 ] || shopt -u nullglob
    if [ "$count" -eq 0 ]; then
        die "no evidence run found under $parent"
    fi
    if [ "$count" -gt 1 ]; then
        die "$parent holds $count runs; this verifier takes exactly one run directory, name it explicitly"
    fi
    printf '%s\n' "$candidate"
}

[ -e "$RUN_DIR_ARG" ] || die "run directory does not exist: $RUN_DIR_ARG"
if [ -L "$RUN_DIR_ARG" ]; then
    die "run directory is a symlink, which this verifier refuses: $RUN_DIR_ARG"
fi
[ -d "$RUN_DIR_ARG" ] || die "run directory is not a directory: $RUN_DIR_ARG"

RESOLVED_INPUT="$(canonical_dir "$RUN_DIR_ARG")"
RUN_DIR_INPUT_KIND="run directory"

if looks_like_run_dir "$RESOLVED_INPUT"; then
    RUN_DIR="$RESOLVED_INPUT"
elif [ "$(basename -- "$RESOLVED_INPUT")" = "$RUN_PARENT_NAME" ]; then
    RUN_DIR_INPUT_KIND="canonical run parent"
    RUN_DIR="$(sole_run_in_parent "$RESOLVED_INPUT")"
elif [ -d "$RESOLVED_INPUT/results/$RUN_PARENT_NAME" ]; then
    RUN_DIR_INPUT_KIND="modules repository root"
    RUN_DIR="$(sole_run_in_parent "$(canonical_dir "$RESOLVED_INPUT/results/$RUN_PARENT_NAME")")"
else
    die "not an evidence run directory, canonical run parent, or modules repository root: $RESOLVED_INPUT"
fi

RUN_DIR="$(canonical_dir "$RUN_DIR")"
looks_like_run_dir "$RUN_DIR" || die "resolved run directory is missing required artifacts: $RUN_DIR"
assert_plain_path "run directory" "$RUN_DIR"

RUN_ID="$(basename -- "$RUN_DIR")"

# ------------------------------------------------------------------------------
# Derive the modules repository from the run directory layout
# ------------------------------------------------------------------------------
RUN_PARENT="$(canonical_dir "$RUN_DIR/..")"
[ "$(basename -- "$RUN_PARENT")" = "$RUN_PARENT_NAME" ] \
    || die "run directory is not under results/$RUN_PARENT_NAME: $RUN_DIR"
RESULTS_DIR="$(canonical_dir "$RUN_PARENT/..")"
[ "$(basename -- "$RESULTS_DIR")" = "results" ] \
    || die "run parent is not under a results/ directory: $RUN_PARENT"
MODULES_REPO="$(canonical_dir "$RESULTS_DIR/..")"
[ -f "$MODULES_REPO/pyproject.toml" ] \
    || die "derived modules repository has no pyproject.toml: $MODULES_REPO"
assert_plain_path "modules repository" "$MODULES_REPO"

if ! LC_ALL=C grep -q '^[[:space:]]*name[[:space:]]*=[[:space:]]*["'"'"']flyto-modules-robotics["'"'"']' \
        "$MODULES_REPO/pyproject.toml"; then
    die "derived repository does not declare the flyto-modules-robotics project: $MODULES_REPO/pyproject.toml"
fi

if [ "$MODULES_REPO" = "$CORE_ROOT" ]; then
    die "the derived modules repository is this Core checkout; refusing"
fi

# ------------------------------------------------------------------------------
# Interpreter selection
# ------------------------------------------------------------------------------
PYTHON_BIN="${FLYTO_VERIFY_PYTHON:-python3}"
case "$PYTHON_BIN" in
    /*) : ;;
    *)
        RESOLVED_PYTHON="$(command -v -- "$PYTHON_BIN" 2>/dev/null || true)"
        [ -n "$RESOLVED_PYTHON" ] || die "interpreter not found on PATH: $PYTHON_BIN"
        PYTHON_BIN="$RESOLVED_PYTHON"
        ;;
esac
[ -x "$PYTHON_BIN" ] || die "interpreter is not executable: $PYTHON_BIN"
assert_plain_path "interpreter" "$PYTHON_BIN"

PYTHON_VERSION="$("$PYTHON_BIN" -c 'import sys; print("%d.%d.%d" % sys.version_info[:3])')" \
    || die "cannot run the selected interpreter: $PYTHON_BIN"
"$PYTHON_BIN" -c 'import sys; raise SystemExit(0 if sys.version_info[:2] >= (3, 9) else 1)' \
    || die "interpreter must be Python 3.9 or newer, got $PYTHON_VERSION from $PYTHON_BIN"

# Build and install are the only stages permitted to run tooling. Keep them
# hermetic: no user site, no network index, no build isolation.
export PYTHONNOUSERSITE=1
export PIP_DISABLE_PIP_VERSION_CHECK=1
export PIP_NO_INPUT=1
unset PYTHONPATH 2>/dev/null || true

# ------------------------------------------------------------------------------
# Scratch space
# ------------------------------------------------------------------------------
TMPROOT="${TMPDIR:-/tmp}"
case "$TMPROOT" in
    */) TMPROOT="${TMPROOT%/}" ;;
esac
[ -d "$TMPROOT" ] || TMPROOT="/tmp"
TMPROOT="$(canonical_dir "$TMPROOT")"

SCRATCH="$(mktemp -d "$TMPROOT/$SCRATCH_PREFIX.XXXXXXXX")" || die "cannot create scratch directory"
SCRATCH="$(canonical_dir "$SCRATCH")"
assert_plain_path "scratch directory" "$SCRATCH"

cleanup_scratch() {
    # Narrow by construction: only ever remove a real directory this run
    # created, under the temporary root, whose basename carries this
    # verifier's prefix and mktemp suffix.
    if [ -n "${SCRATCH:-}" ] && [ -d "$SCRATCH" ] && [ ! -L "$SCRATCH" ]; then
        case "$(basename -- "$SCRATCH")" in
            "$SCRATCH_PREFIX".????????)
                case "$SCRATCH" in
                    "$TMPROOT"/*) rm -rf -- "$SCRATCH" ;;
                esac
                ;;
        esac
    fi
}
trap 'cleanup_scratch' EXIT
trap 'trap - EXIT; cleanup_scratch; exit 130' INT
trap 'trap - EXIT; cleanup_scratch; exit 143' TERM

BUILD_SRC="$SCRATCH/source"
WHEELHOUSE="$SCRATCH/wheelhouse"
TARGET="$SCRATCH/target"
mkdir -p -- "$BUILD_SRC" "$WHEELHOUSE" "$TARGET"

# ------------------------------------------------------------------------------
# Copy the modules source into scratch, then build there.
#
# `--no-isolation` builds in place, and building in place would leave build/,
# dist/ and *.egg-info behind in a repository this closure does not own. Copy
# first; the source repository stays byte-identical.
# ------------------------------------------------------------------------------
note "copying flyto-modules-robotics source into scratch (the repository is never written to)"
(
    cd -P -- "$MODULES_REPO" && tar -cf - \
        --exclude './results' \
        --exclude './.git' \
        --exclude './build' \
        --exclude './dist' \
        --exclude './.venv' \
        --exclude './.tox' \
        --exclude './.mypy_cache' \
        --exclude './.pytest_cache' \
        --exclude './.flyto-index' \
        --exclude '*.egg-info' \
        --exclude '__pycache__' \
        .
) | ( cd -P -- "$BUILD_SRC" && tar -xf - ) \
    || die "failed to copy the modules source tree into scratch"

[ -f "$BUILD_SRC/pyproject.toml" ] || die "scratch source copy is missing pyproject.toml"

BUILD_COMMAND="python -m build --wheel --no-isolation --outdir <scratch>/wheelhouse <scratch>/source"
note "building exactly one wheel with $PYTHON_BIN ($PYTHON_VERSION)"
if ! "$PYTHON_BIN" -m build --wheel --no-isolation --outdir "$WHEELHOUSE" "$BUILD_SRC" \
        >"$SCRATCH/build.log" 2>&1; then
    sed -e 's/^/    build| /' "$SCRATCH/build.log" >&2 || true
    die "wheel build failed"
fi

WHEEL_PATH=""
WHEEL_COUNT=0
shopt -s nullglob
for wheel_candidate in "$WHEELHOUSE"/*.whl; do
    WHEEL_PATH="$wheel_candidate"
    WHEEL_COUNT=$((WHEEL_COUNT + 1))
done
shopt -u nullglob
[ "$WHEEL_COUNT" -eq 1 ] || die "expected exactly one built wheel, found $WHEEL_COUNT in $WHEELHOUSE"
WHEEL_NAME="$(basename -- "$WHEEL_PATH")"
[ "$WHEEL_NAME" = "flyto_modules_robotics-0.1.1-py3-none-any.whl" ] \
    || die "built wheel is not flyto_modules_robotics-0.1.1-py3-none-any.whl, got: $WHEEL_NAME"
assert_plain_path "wheel" "$WHEEL_PATH"

INSTALL_COMMAND="pip install --no-index --no-deps --target <scratch>/target <wheel>"
note "installing the wheel offline into a throwaway target"
if ! "$PYTHON_BIN" -m pip install --no-index --no-deps --target "$TARGET" "$WHEEL_PATH" \
        >"$SCRATCH/install.log" 2>&1; then
    sed -e 's/^/    install| /' "$SCRATCH/install.log" >&2 || true
    die "offline wheel install failed"
fi

# ------------------------------------------------------------------------------
# Unique, durable result directory inside this Core checkout
# ------------------------------------------------------------------------------
STAMP="$(date -u +%Y%m%dT%H%M%SZ)"
RESULT_ROOT="$CORE_ROOT/test-results/robotics-registration"
RESULT_DIR="$RESULT_ROOT/$RUN_ID-$STAMP-$$"
if [ -e "$RESULT_DIR" ]; then
    die "result directory already exists, refusing to reuse it: $RESULT_DIR"
fi
mkdir -p -- "$RESULT_DIR/evidence" || die "cannot create result directory: $RESULT_DIR"
RESULT_DIR="$(canonical_dir "$RESULT_DIR")"
assert_plain_path "result directory" "$RESULT_DIR"

# ------------------------------------------------------------------------------
# Config for the embedded verifier
# ------------------------------------------------------------------------------
CONFIG="$SCRATCH/config.json"
{
    printf '{\n'
    printf '  "run_dir": "%s",\n'                "$RUN_DIR"
    printf '  "run_id": "%s",\n'                 "$RUN_ID"
    printf '  "run_dir_input": "%s",\n'          "$RESOLVED_INPUT"
    printf '  "run_dir_input_kind": "%s",\n'     "$RUN_DIR_INPUT_KIND"
    printf '  "core_root": "%s",\n'              "$CORE_ROOT"
    printf '  "core_src": "%s",\n'               "$CORE_SRC"
    printf '  "modules_repo": "%s",\n'           "$MODULES_REPO"
    printf '  "build_source": "%s",\n'           "$BUILD_SRC"
    printf '  "wheel_path": "%s",\n'             "$WHEEL_PATH"
    printf '  "wheel_filename": "%s",\n'         "$WHEEL_NAME"
    printf '  "target": "%s",\n'                 "$TARGET"
    printf '  "scratch": "%s",\n'                "$SCRATCH"
    printf '  "result_dir": "%s",\n'             "$RESULT_DIR"
    printf '  "python_executable": "%s",\n'      "$PYTHON_BIN"
    printf '  "python_version": "%s",\n'         "$PYTHON_VERSION"
    printf '  "build_command": "%s",\n'          "$BUILD_COMMAND"
    printf '  "install_command": "%s",\n'        "$INSTALL_COMMAND"
    printf '  "max_age_seconds": %s,\n'          "$MAX_AGE_SECONDS"
    printf '  "max_age_source": "%s",\n'         "$MAX_AGE_SOURCE"
    printf '  "default_max_age_seconds": %s,\n'  "$DEFAULT_MAX_AGE_SECONDS"
    printf '  "hard_max_age_seconds": %s\n'      "$HARD_MAX_AGE_SECONDS"
    printf '}\n'
} >"$CONFIG"

VERIFIER="$SCRATCH/verify_registration.py"
cat >"$VERIFIER" <<'PYEOF'
"""Embedded Core-side robotics registration verifier.

Reads one finished evidence run, copies it, exercises the real public
ModuleRegistry surface against an offline-installed flyto-modules-robotics
wheel, and writes one atomic report.

It must not shell out, must not reach the network, and must not touch anything
outside the scratch directory and the unique Core result directory. Those
constraints are enforced below, not merely documented.
"""

import asyncio
import datetime as _dt
import hashlib
import io
import json
import logging
import os
import stat
import sys

CONTRACT = "flyto.core.robotics-registration.v1"
DEVICE_ID = "core-verify-robot-001"
CONTEXT = {"resource_id": DEVICE_ID}

UPPER_REPORT_CONTRACT = "flyto.modules-robotics.gazebo-closed-loop.v1"
UPPER_CLEANUP_CONTRACT = "flyto.modules-robotics.gazebo-cleanup.v1"
LOWER_REPORT_CONTRACT = "flyto.robotics.burger-gazebo-acceptance.v1"
LOWER_CLEANUP_CONTRACT = "flyto.robotics.runtime-cleanup.v1"
REQUEST_CONTRACT = "flyto.cloud.plan-run-request.v1"
PLAN_CONTRACT = "flyto.robotics.plan.v1"

ENTRY_POINT_GROUP = "flyto.modules"
ENTRY_POINT_NAME = "robotics"
ENTRY_POINT_VALUE = "flyto_modules_robotics:register_all"
DISTRIBUTION_NAME = "flyto-modules-robotics"
DISTRIBUTION_VERSION = "0.1.1"

EXPECTED_MODULE_IDS = ["robotics.move", "robotics.stop", "robotics.turn"]
MODULE_PARAMS = {
    "robotics.move": {"distance_m": 0.05, "speed": 0.05},
    "robotics.stop": {"seconds": 0},
    "robotics.turn": {"degrees": 15, "angular_speed": 0.4},
}

LOWER_RESULTS_PARENT = "virtual-robot"
SAFE_STOP = "safe_stop"

HOSTISH_KEYS = frozenset([
    "host", "hostname", "url", "uri", "endpoint", "base_url", "baseurl",
    "gateway_url", "address", "addr", "netloc", "origin",
])

# Invariant keys. Each is proven unless something recorded a failure against it,
# so a report never claims an invariant held merely because nothing looked, and
# never blanket-denies invariants that a different failure did not touch.
INVARIANTS = [
    "run_dir_resolved_and_contained",
    "upper_report_contract_and_pass_facts",
    "upper_cleanup_contract_run_id_and_final_status",
    "upper_restoration_and_quiescence_facts",
    "lower_evidence_has_no_contract_version",
    "lower_evidence_equals_report_lower_layer",
    "lower_report_contract_and_pass_facts",
    "lower_cleanup_contract_zero_command_and_status",
    "lower_paths_contained_and_regular_files",
    "declared_sha256_recomputed_and_matched",
    "evidence_files_are_regular_and_not_symlinks",
    "evidence_not_future_and_within_max_age",
    "five_evidence_files_copied_with_matching_hashes",
    "exactly_one_robotics_entry_point",
    "robotics_distribution_identity_inside_target",
    "import_origins_are_target_then_core_src",
    "robotics_plugin_loaded_without_discovery_error",
    "owned_module_ids_exactly_move_stop_turn",
    "declarations_are_not_dispatched",
    "declarations_bound_to_synthetic_device",
    "requests_use_plan_run_request_v1",
    "plan_contract_schema_is_the_canonical_lower_contract",
    "plans_satisfy_plan_v1_schema",
    "plans_end_with_safe_stop",
    "declarations_contain_no_host_url_or_uri",
    "execution_context_unchanged",
]

failures = []
invariant_failures = {}


def fail(message, inv=None):
    failures.append(message)
    if inv is not None:
        invariant_failures.setdefault(inv, []).append(message)


def require(condition, message, inv=None):
    if not condition:
        fail(message, inv)
    return bool(condition)


def require_exact(label, actual, expected, inv=None):
    if actual != expected or type(actual) is not type(expected):
        fail("%s: expected %r (%s), got %r (%s)"
             % (label, expected, type(expected).__name__,
                actual, type(actual).__name__), inv)
        return False
    return True


def require_true(label, value, inv=None):
    if value is not True:
        fail("%s: expected the boolean True, got %r" % (label, value), inv)
        return False
    return True


def require_false(label, value, inv=None):
    if value is not False:
        fail("%s: expected the boolean False, got %r" % (label, value), inv)
        return False
    return True


# ------------------------------------------------------------------------------
# Non-actuation guards
# ------------------------------------------------------------------------------
class NonActuatingViolation(RuntimeError):
    """Raised when verified code tries to act on the world."""


def install_non_actuation_guards():
    """Make shelling out and reaching the network impossible, not merely unwise."""
    def blocked(what):
        def _blocked(*_args, **_kwargs):
            raise NonActuatingViolation(
                "%s is forbidden inside the Core robotics registration verifier" % what
            )
        return _blocked

    import subprocess  # imported solely so its callables can be disabled
    for name in ("Popen", "run", "call", "check_call", "check_output",
                 "getoutput", "getstatusoutput"):
        if hasattr(subprocess, name):
            setattr(subprocess, name, blocked("subprocess.%s" % name))

    for name in ("system", "popen", "execv", "execve", "execvp", "execvpe",
                 "spawnv", "spawnve", "spawnvp", "spawnvpe", "posix_spawn",
                 "posix_spawnp", "fork", "forkpty"):
        if hasattr(os, name):
            setattr(os, name, blocked("os.%s" % name))

    # Sockets are blocked at connection and resolution, not construction:
    # asyncio builds its own AF_UNIX self-pipe with socketpair() and must keep
    # working. What matters is that nothing can reach off this machine.
    import socket
    for name in ("create_connection", "create_server", "getaddrinfo",
                 "gethostbyname", "gethostbyname_ex", "gethostbyaddr"):
        if hasattr(socket, name):
            setattr(socket, name, blocked("socket.%s" % name))
    for name in ("connect", "connect_ex", "sendto"):
        if hasattr(socket.socket, name):
            setattr(socket.socket, name, blocked("socket.socket.%s" % name))


# ------------------------------------------------------------------------------
# Small helpers
# ------------------------------------------------------------------------------
def sha256_bytes(data):
    return hashlib.sha256(data).hexdigest()


def sha256_file(path):
    digest = hashlib.sha256()
    with open(path, "rb") as handle:
        while True:
            chunk = handle.read(1024 * 1024)
            if not chunk:
                break
            digest.update(chunk)
    return digest.hexdigest()


def read_regular_file(label, path, contained_in, inv):
    """Read a file only if it is an unremarkable, contained, regular file."""
    if not isinstance(path, str) or not os.path.isabs(path):
        fail("%s path is not an absolute path: %r" % (label, path), inv)
        return None
    normalised = os.path.normpath(path)
    if normalised != path:
        fail("%s path is not normalised: %s" % (label, path), inv)
        return None
    root = os.path.normpath(contained_in)
    if not (normalised == root or normalised.startswith(root + os.sep)):
        fail("%s path escapes %s: %s" % (label, root, path), inv)
        return None
    try:
        info = os.lstat(normalised)
    except OSError as exc:
        fail("%s is unreachable: %s (%s)" % (label, path, exc), inv)
        return None
    if stat.S_ISLNK(info.st_mode):
        fail("%s is a symlink, which this verifier refuses: %s" % (label, path),
             "evidence_files_are_regular_and_not_symlinks")
        return None
    if not stat.S_ISREG(info.st_mode):
        fail("%s is not a regular file: %s" % (label, path),
             "evidence_files_are_regular_and_not_symlinks")
        return None
    if os.path.realpath(normalised) != normalised:
        fail("%s resolves through a symlink: %s -> %s"
             % (label, path, os.path.realpath(normalised)),
             "evidence_files_are_regular_and_not_symlinks")
        return None
    try:
        with open(normalised, "rb") as handle:
            data = handle.read()
    except OSError as exc:
        fail("%s cannot be read: %s (%s)" % (label, path, exc), inv)
        return None
    return {
        "path": normalised,
        "bytes": data,
        "sha256": sha256_bytes(data),
        "mtime": info.st_mtime,
        "size": info.st_size,
    }


def parse_json(label, data, inv):
    try:
        return json.loads(data.decode("utf-8"))
    except Exception as exc:
        fail("%s is not valid UTF-8 JSON: %s" % (label, exc), inv)
        return None


def parse_utc(label, text, inv):
    if not isinstance(text, str):
        fail("%s is not a string timestamp: %r" % (label, text), inv)
        return None
    raw = text.strip()
    if not raw.endswith("Z"):
        fail("%s is not an explicit UTC timestamp ending in Z: %r" % (label, text), inv)
        return None
    for pattern in ("%Y-%m-%dT%H:%M:%SZ", "%Y-%m-%dT%H:%M:%S.%fZ"):
        try:
            parsed = _dt.datetime.strptime(raw, pattern)
        except ValueError:
            continue
        return parsed.replace(tzinfo=_dt.timezone.utc)
    fail("%s is not an ISO-8601 UTC timestamp: %r" % (label, text), inv)
    return None


def walk(node, path="$"):
    yield path, node
    if isinstance(node, dict):
        for key in node:
            for item in walk(node[key], "%s.%s" % (path, key)):
                yield item
    elif isinstance(node, list):
        for index, value in enumerate(node):
            for item in walk(value, "%s[%d]" % (path, index)):
                yield item


def find_contract_objects(node, contract):
    return [(path, value) for path, value in walk(node)
            if isinstance(value, dict) and value.get("contract_version") == contract]


def find_key(node, key):
    found = []
    for path, value in walk(node):
        if isinstance(value, dict) and key in value:
            found.append(("%s.%s" % (path, key), value[key]))
    return found


# ------------------------------------------------------------------------------
# flyto.robotics.plan.v1 is not this verifier's contract to define.
#
# An earlier revision embedded a hand-written subset of the plan schema here.
# It "validated" plans against what Core happened to expect and rejected
# canonical fields - goal, generated_by, step_id, timeout_seconds, on_failure -
# that the real contract requires. A schema invented by the checker proves
# nothing about the contract; it only proves the checker agrees with itself.
#
# The canonical schema is read from the lower repository the evidence itself
# points at, hashed, sanity-checked, and then applied verbatim.
# ------------------------------------------------------------------------------
PLAN_SCHEMA_RELPATH = os.path.join("contracts", "plan-v1.schema.json")

# Keywords this validator implements and enforces.
_ASSERTION_KEYWORDS = frozenset([
    "$ref",
    "type", "enum", "const",
    "properties", "required", "additionalProperties", "patternProperties",
    "propertyNames", "minProperties", "maxProperties",
    "dependentRequired", "dependentSchemas", "dependencies",
    "items", "prefixItems", "additionalItems", "contains",
    "minItems", "maxItems", "uniqueItems",
    "minimum", "maximum", "exclusiveMinimum", "exclusiveMaximum", "multipleOf",
    "minLength", "maxLength", "pattern",
    "allOf", "anyOf", "oneOf", "not", "if", "then", "else",
])

# Keywords that annotate rather than constrain. Ignoring these is correct;
# anything outside both sets is refused, so the validator can never quietly
# under-check a contract it does not fully implement.
_ANNOTATION_KEYWORDS = frozenset([
    "$schema", "$id", "id", "$anchor", "$comment", "$defs", "definitions",
    "title", "description", "default", "examples", "deprecated",
    "readOnly", "writeOnly", "format", "contentMediaType", "contentEncoding",
])


class SchemaError(Exception):
    """The contract schema itself is malformed or beyond this validator."""


def _resolve_ref(ref, root):
    if not isinstance(ref, str) or not ref.startswith("#"):
        raise SchemaError("only local JSON pointers are supported, got %r" % (ref,))
    pointer = ref[1:]
    node = root
    if pointer in ("", "/"):
        return node
    for raw in pointer.lstrip("/").split("/"):
        token = raw.replace("~1", "/").replace("~0", "~")
        if isinstance(node, dict):
            if token not in node:
                raise SchemaError("unresolvable JSON pointer %r" % (ref,))
            node = node[token]
        elif isinstance(node, list):
            try:
                node = node[int(token)]
            except (ValueError, IndexError):
                raise SchemaError("unresolvable JSON pointer %r" % (ref,))
        else:
            raise SchemaError("unresolvable JSON pointer %r" % (ref,))
    return node


def _deref(schema, root, depth=0):
    while isinstance(schema, dict) and "$ref" in schema and depth < 32:
        schema = _resolve_ref(schema["$ref"], root)
        depth += 1
    return schema


def _type_matches(instance, name):
    if name == "null":
        return instance is None
    if name == "boolean":
        return isinstance(instance, bool)
    if name == "integer":
        return isinstance(instance, int) and not isinstance(instance, bool)
    if name == "number":
        return isinstance(instance, (int, float)) and not isinstance(instance, bool)
    if name == "string":
        return isinstance(instance, str)
    if name == "array":
        return isinstance(instance, list)
    if name == "object":
        return isinstance(instance, dict)
    raise SchemaError("unknown JSON Schema type %r" % (name,))


def _json_equal(left, right):
    # JSON equality, except that True == 1 must not hold.
    if isinstance(left, bool) != isinstance(right, bool):
        return False
    if isinstance(left, dict) and isinstance(right, dict):
        return (set(left) == set(right)
                and all(_json_equal(left[key], right[key]) for key in left))
    if isinstance(left, list) and isinstance(right, list):
        return (len(left) == len(right)
                and all(_json_equal(a, b) for a, b in zip(left, right)))
    return left == right


def validate_schema(instance, schema, root=None, path="$", errors=None):
    """Validate `instance` against `schema`, collecting every violation.

    Supports the draft-07 / 2020-12 assertion vocabulary listed above. Any
    keyword outside the known assertion and annotation sets raises SchemaError
    rather than being skipped: a contract this verifier cannot fully enforce
    must stop the run, not silently pass it.
    """
    if errors is None:
        errors = []
    if root is None:
        root = schema
    if schema is True:
        return errors
    if schema is False:
        errors.append("%s: schema permits no value here" % path)
        return errors
    if not isinstance(schema, dict):
        raise SchemaError("%s: schema fragment is not an object or boolean" % path)

    for keyword in schema:
        if keyword not in _ASSERTION_KEYWORDS and keyword not in _ANNOTATION_KEYWORDS:
            raise SchemaError(
                "%s: unsupported JSON Schema keyword %r; this verifier refuses to "
                "under-validate a contract it does not fully implement" % (path, keyword))

    if "$ref" in schema:
        validate_schema(instance, _resolve_ref(schema["$ref"], root), root, path, errors)

    # ---- any instance -------------------------------------------------------
    if "type" in schema:
        names = schema["type"]
        names = names if isinstance(names, list) else [names]
        if not any(_type_matches(instance, name) for name in names):
            errors.append("%s: expected type %s, got %s"
                          % (path, "/".join(names), type(instance).__name__))
            return errors
    if "const" in schema and not _json_equal(instance, schema["const"]):
        errors.append("%s: expected constant %r, got %r" % (path, schema["const"], instance))
    if "enum" in schema and not any(_json_equal(instance, value) for value in schema["enum"]):
        errors.append("%s: %r is not one of %r" % (path, instance, schema["enum"]))

    for keyword, combine in (("allOf", "all"), ("anyOf", "any"), ("oneOf", "one")):
        if keyword not in schema:
            continue
        branches = schema[keyword]
        outcomes = []
        for index, branch in enumerate(branches):
            branch_errors = validate_schema(
                instance, branch, root, "%s/%s[%d]" % (path, keyword, index), [])
            outcomes.append(branch_errors)
        matched = sum(1 for branch_errors in outcomes if not branch_errors)
        if combine == "all":
            for branch_errors in outcomes:
                errors.extend(branch_errors)
        elif combine == "any" and matched == 0:
            errors.append("%s: matched none of the %d anyOf branches" % (path, len(branches)))
        elif combine == "one" and matched != 1:
            errors.append("%s: matched %d oneOf branches, expected exactly 1"
                          % (path, matched))
    if "not" in schema:
        if not validate_schema(instance, schema["not"], root, "%s/not" % path, []):
            errors.append("%s: matched a schema it must not match" % path)
    if "if" in schema:
        condition_met = not validate_schema(instance, schema["if"], root, "%s/if" % path, [])
        branch = "then" if condition_met else "else"
        if branch in schema:
            validate_schema(instance, schema[branch], root, "%s/%s" % (path, branch), errors)

    # ---- strings ------------------------------------------------------------
    if isinstance(instance, str):
        if "minLength" in schema and len(instance) < schema["minLength"]:
            errors.append("%s: shorter than minLength %d" % (path, schema["minLength"]))
        if "maxLength" in schema and len(instance) > schema["maxLength"]:
            errors.append("%s: longer than maxLength %d" % (path, schema["maxLength"]))
        if "pattern" in schema:
            import re as _re
            if _re.search(schema["pattern"], instance) is None:
                errors.append("%s: %r does not match pattern %r"
                              % (path, instance, schema["pattern"]))

    # ---- numbers ------------------------------------------------------------
    if isinstance(instance, (int, float)) and not isinstance(instance, bool):
        if "minimum" in schema and instance < schema["minimum"]:
            errors.append("%s: %r is below minimum %r" % (path, instance, schema["minimum"]))
        if "maximum" in schema and instance > schema["maximum"]:
            errors.append("%s: %r is above maximum %r" % (path, instance, schema["maximum"]))
        if "exclusiveMinimum" in schema and instance <= schema["exclusiveMinimum"]:
            errors.append("%s: %r is not above exclusiveMinimum %r"
                          % (path, instance, schema["exclusiveMinimum"]))
        if "exclusiveMaximum" in schema and instance >= schema["exclusiveMaximum"]:
            errors.append("%s: %r is not below exclusiveMaximum %r"
                          % (path, instance, schema["exclusiveMaximum"]))
        if "multipleOf" in schema:
            divisor = schema["multipleOf"]
            if divisor <= 0 or (instance % divisor) != 0:
                errors.append("%s: %r is not a multiple of %r" % (path, instance, divisor))

    # ---- objects ------------------------------------------------------------
    if isinstance(instance, dict):
        properties = schema.get("properties", {})
        pattern_properties = schema.get("patternProperties", {})
        for key in schema.get("required", []):
            if key not in instance:
                errors.append("%s: missing required property %r" % (path, key))
        if "minProperties" in schema and len(instance) < schema["minProperties"]:
            errors.append("%s: fewer than minProperties %d" % (path, schema["minProperties"]))
        if "maxProperties" in schema and len(instance) > schema["maxProperties"]:
            errors.append("%s: more than maxProperties %d" % (path, schema["maxProperties"]))
        for key in sorted(properties):
            if key in instance:
                validate_schema(instance[key], properties[key], root,
                                "%s.%s" % (path, key), errors)
        if pattern_properties:
            import re as _re
            for expression in sorted(pattern_properties):
                for key in sorted(instance):
                    if _re.search(expression, key) is not None:
                        validate_schema(instance[key], pattern_properties[expression], root,
                                        "%s.%s" % (path, key), errors)
        if "additionalProperties" in schema:
            import re as _re
            extra = schema["additionalProperties"]
            for key in sorted(instance):
                if key in properties:
                    continue
                if any(_re.search(expression, key) is not None
                       for expression in pattern_properties):
                    continue
                if extra is False:
                    errors.append(
                        "%s: unexpected property %r (additionalProperties is false)"
                        % (path, key))
                else:
                    validate_schema(instance[key], extra, root,
                                    "%s.%s" % (path, key), errors)
        if "propertyNames" in schema:
            for key in sorted(instance):
                validate_schema(key, schema["propertyNames"], root,
                                "%s/propertyNames.%s" % (path, key), errors)
        for keyword in ("dependentRequired", "dependencies", "dependentSchemas"):
            for key, dependency in sorted(schema.get(keyword, {}).items()):
                if key not in instance:
                    continue
                if isinstance(dependency, list):
                    for needed in dependency:
                        if needed not in instance:
                            errors.append("%s: property %r requires %r"
                                          % (path, key, needed))
                else:
                    validate_schema(instance, dependency, root,
                                    "%s/%s[%s]" % (path, keyword, key), errors)

    # ---- arrays -------------------------------------------------------------
    if isinstance(instance, list):
        if "minItems" in schema and len(instance) < schema["minItems"]:
            errors.append("%s: expected at least %d item(s), got %d"
                          % (path, schema["minItems"], len(instance)))
        if "maxItems" in schema and len(instance) > schema["maxItems"]:
            errors.append("%s: expected at most %d item(s), got %d"
                          % (path, schema["maxItems"], len(instance)))
        if schema.get("uniqueItems") is True:
            for i in range(len(instance)):
                for j in range(i + 1, len(instance)):
                    if _json_equal(instance[i], instance[j]):
                        errors.append("%s: items %d and %d are duplicates" % (path, i, j))
        prefix = schema.get("prefixItems")
        offset = 0
        if prefix is not None:
            for index, subschema in enumerate(prefix):
                if index < len(instance):
                    validate_schema(instance[index], subschema, root,
                                    "%s[%d]" % (path, index), errors)
            offset = len(prefix)
        item_schema = schema.get("items")
        if isinstance(item_schema, list):
            # draft-07 tuple form
            for index, subschema in enumerate(item_schema):
                if index < len(instance):
                    validate_schema(instance[index], subschema, root,
                                    "%s[%d]" % (path, index), errors)
            offset = len(item_schema)
            extra_items = schema.get("additionalItems")
            if extra_items is not None:
                for index in range(offset, len(instance)):
                    if extra_items is False:
                        errors.append("%s[%d]: additionalItems is false" % (path, index))
                    else:
                        validate_schema(instance[index], extra_items, root,
                                        "%s[%d]" % (path, index), errors)
        elif item_schema is not None:
            for index in range(offset, len(instance)):
                validate_schema(instance[index], item_schema, root,
                                "%s[%d]" % (path, index), errors)
        if "contains" in schema:
            if not any(not validate_schema(item, schema["contains"], root, path, [])
                       for item in instance):
                errors.append("%s: no item satisfies `contains`" % path)
    return errors


def load_plan_contract(lower_repo, inv):
    """Read, hash and sanity-check the canonical flyto.robotics.plan.v1 schema.

    The schema is trusted to define the contract, but not blindly: it must still
    be the closed, capability-requiring shape this closure depends on, and it
    must not have grown a module_id requirement, which plan v1 does not have.
    """
    path = os.path.join(lower_repo, PLAN_SCHEMA_RELPATH)
    entry = read_regular_file("plan v1 contract schema", path, lower_repo, inv)
    if entry is None:
        return None, None
    schema = parse_json("plan v1 contract schema", entry["bytes"], inv)
    if not isinstance(schema, dict):
        fail("plan v1 contract schema is not a JSON object: %s" % path, inv)
        return None, {"path": entry["path"], "sha256": entry["sha256"],
                      "size_bytes": entry["size"], "usable": False}

    try:
        plan_schema = _deref(schema, schema)
        if not isinstance(plan_schema, dict):
            raise SchemaError("the plan schema root is not an object")
        plan_properties = plan_schema.get("properties", {})
        plan_properties = plan_properties if isinstance(plan_properties, dict) else {}
        steps_schema = _deref(plan_properties.get("steps", {}), schema)
        steps_schema = steps_schema if isinstance(steps_schema, dict) else {}
        # A tuple-form `items` would mean plan steps are positional, which plan v1
        # is not; leave step_schema empty so the shape checks below say so aloud.
        step_schema = _deref(steps_schema.get("items", {}), schema)
        step_schema = step_schema if isinstance(step_schema, dict) else {}
    except SchemaError as exc:
        fail("plan v1 contract schema cannot be resolved: %s" % exc, inv)
        return None, {"path": entry["path"], "sha256": entry["sha256"],
                      "size_bytes": entry["size"], "usable": False}

    plan_required = list(plan_schema.get("required", []) or [])
    step_required = list(step_schema.get("required", []) or [])

    require(plan_schema.get("additionalProperties") is False,
            "plan v1 contract schema does not close additionalProperties on the plan "
            "object", inv)
    require(step_schema.get("additionalProperties") is False,
            "plan v1 contract schema does not close additionalProperties on a plan step",
            inv)
    require("capability" in step_required,
            "plan v1 contract schema does not require `capability` on a plan step", inv)
    require("module_id" not in plan_required and "module_id" not in step_required,
            "plan v1 contract schema requires module_id; plan v1 has no such field and "
            "this verifier will not adopt an invented one", inv)

    pinned = plan_properties.get("contract_version")
    if isinstance(pinned, dict):
        if "const" in pinned:
            require_exact("plan v1 contract schema contract_version const",
                          pinned["const"], PLAN_CONTRACT, inv)
        elif "enum" in pinned:
            require_exact("plan v1 contract schema contract_version enum",
                          list(pinned["enum"]), [PLAN_CONTRACT], inv)

    return schema, {
        "path": entry["path"],
        "sha256": entry["sha256"],
        "size_bytes": entry["size"],
        "source_repository": lower_repo,
        "plan_required": sorted(plan_required),
        "plan_additional_properties_closed": plan_schema.get("additionalProperties") is False,
        "step_required": sorted(step_required),
        "step_additional_properties_closed": step_schema.get("additionalProperties") is False,
        "plan_properties": sorted(plan_properties),
        "step_properties": sorted(step_schema.get("properties", {}) or {}),
        "requires_module_id": "module_id" in plan_required or "module_id" in step_required,
    }


# ------------------------------------------------------------------------------
# Atomic, durable write: same directory, rename, fsync file and directory.
# ------------------------------------------------------------------------------
def write_atomic_json(path, payload):
    directory = os.path.dirname(path)
    temporary = os.path.join(
        directory, ".%s.tmp.%d" % (os.path.basename(path), os.getpid()))
    body = json.dumps(payload, indent=2, sort_keys=True, ensure_ascii=False) + "\n"
    data = body.encode("utf-8")
    descriptor = os.open(temporary, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o644)
    try:
        with io.open(descriptor, "wb", closefd=True) as stream:
            stream.write(data)
            stream.flush()
            os.fsync(stream.fileno())
    except Exception:
        try:
            os.unlink(temporary)
        except OSError:
            pass
        raise
    os.replace(temporary, path)
    directory_fd = os.open(directory, os.O_RDONLY)
    try:
        os.fsync(directory_fd)
    finally:
        os.close(directory_fd)
    return sha256_bytes(data)


# ==============================================================================
# Declaration inspection
# ==============================================================================
def inspect_declaration(module_id, params, result, plan_schema):
    """Check one module result is a plan declaration and nothing more."""
    payload = result
    # Modules answer with the Core success envelope; the declaration is inside.
    for _ in range(4):
        if isinstance(payload, dict) and "data" in payload and "dispatched" not in payload:
            payload = payload["data"]
        else:
            break

    dispatched = find_key(payload, "dispatched")
    if require(len(dispatched) >= 1,
               "%s: result declares no `dispatched` field" % module_id,
               "declarations_are_not_dispatched"):
        for path, value in dispatched:
            require_false("%s: %s" % (module_id, path), value,
                          "declarations_are_not_dispatched")

    device = find_key(payload, "requires_device")
    if require(len(device) >= 1,
               "%s: result declares no `requires_device` field" % module_id,
               "declarations_bound_to_synthetic_device"):
        for path, value in device:
            require_exact("%s: %s" % (module_id, path), value, DEVICE_ID,
                          "declarations_bound_to_synthetic_device")

    requests = find_contract_objects(payload, REQUEST_CONTRACT)
    require(len(requests) == 1,
            "%s: expected exactly one %s object, found %d"
            % (module_id, REQUEST_CONTRACT, len(requests)),
            "requests_use_plan_run_request_v1")

    plans = find_contract_objects(payload, PLAN_CONTRACT)
    require(len(plans) == 1,
            "%s: expected exactly one %s object, found %d"
            % (module_id, PLAN_CONTRACT, len(plans)),
            "plans_satisfy_plan_v1_schema")

    plan = plans[0][1] if len(plans) == 1 else {}
    if len(requests) == 1 and len(plans) == 1:
        require(plans[0][0].startswith(requests[0][0]),
                "%s: the plan is not carried inside the plan-run request (%s vs %s)"
                % (module_id, plans[0][0], requests[0][0]),
                "requests_use_plan_run_request_v1")

    if not plan:
        schema_errors = ["$.plan: no %s object was produced" % PLAN_CONTRACT]
    elif plan_schema is None:
        schema_errors = ["$.plan: the canonical %s schema could not be loaded"
                         % PLAN_CONTRACT]
    else:
        try:
            schema_errors = validate_schema(plan, plan_schema, plan_schema, "$.plan", [])
        except SchemaError as exc:
            schema_errors = ["$.plan: %s" % exc]
    for message in schema_errors:
        fail("%s: plan does not satisfy %s: %s" % (module_id, PLAN_CONTRACT, message),
             "plans_satisfy_plan_v1_schema")

    require_exact("%s: plan.robot_id" % module_id, plan.get("robot_id"), DEVICE_ID,
                  "declarations_bound_to_synthetic_device")

    steps = plan.get("steps") if isinstance(plan.get("steps"), list) else []
    require(len(steps) >= 1, "%s: plan has no steps" % module_id,
            "plans_satisfy_plan_v1_schema")

    final_capability = None
    if steps and isinstance(steps[-1], dict):
        final_capability = steps[-1].get("capability")
    require_exact("%s: final step capability" % module_id, final_capability, SAFE_STOP,
                  "plans_end_with_safe_stop")

    # Nothing in a declaration may name a host, URL, endpoint or URI. A plan that
    # knows where to go is a plan that could be persuaded to go there.
    for path, value in walk(payload):
        if isinstance(value, dict):
            for key in value:
                if isinstance(key, str) and key.lower() in HOSTISH_KEYS:
                    fail("%s: declaration exposes a host-like key at %s.%s"
                         % (module_id, path, key),
                         "declarations_contain_no_host_url_or_uri")
        if isinstance(value, str) and "://" in value:
            fail("%s: declaration embeds a URI at %s: %r" % (module_id, path, value),
                 "declarations_contain_no_host_url_or_uri")

    return {
        "params": params,
        "context": dict(CONTEXT),
        "dispatched_occurrences": [
            {"path": path, "value": value} for path, value in dispatched],
        "requires_device_occurrences": [
            {"path": path, "value": value} for path, value in device],
        "request_contract_version": (
            requests[0][1].get("contract_version") if len(requests) == 1 else None),
        "request_path": requests[0][0] if len(requests) == 1 else None,
        "plan_contract_version": plan.get("contract_version"),
        "plan_id": plan.get("plan_id"),
        "plan_robot_id": plan.get("robot_id"),
        "plan_step_count": len(steps),
        "plan_step_capabilities": [
            step.get("capability") for step in steps if isinstance(step, dict)],
        "final_step_capability": final_capability,
        "plan_schema_violations": schema_errors,
    }


# ==============================================================================
# Report
# ==============================================================================
def build_report(cfg, started_at, state):
    passed = not failures
    finished = _dt.datetime.now(_dt.timezone.utc)

    wheel_path = cfg["wheel_path"]
    report = {
        "contract_version": CONTRACT,
        "passed": passed,
        "run_id": cfg["run_id"],
        "scope": (
            "Registration and declaration evidence for the flyto-modules-robotics "
            "wheel inside this flyto-core checkout, cross-checked against one "
            "finished Gazebo simulation run. Every physical claim restated here is "
            "simulation-derived: this is NOT physical-hardware evidence. The "
            "verifier itself is non-actuating - no hardware, ROS, Gazebo, Lima, "
            "gateway, dispatch, cmd_vel publication, network, SSH or login action "
            "was taken, and subprocess execution plus outbound networking were "
            "disabled inside the verifying interpreter."
        ),
        "scope_flags": {
            "simulation_derived": True,
            "physical_hardware_evidence": False,
            "actuating": False,
            "dispatched_any_plan": False,
            "published_cmd_vel": False,
            "started_ros_gazebo_or_lima": False,
            "used_network_ssh_or_login": False,
        },
        "generated_at": finished.strftime("%Y-%m-%dT%H:%M:%S.%fZ"),
        "freshness": {
            "verifier_started_at": started_at.strftime("%Y-%m-%dT%H:%M:%S.%fZ"),
            "verifier_finished_at": finished.strftime("%Y-%m-%dT%H:%M:%S.%fZ"),
            "verifier_duration_seconds": round(
                (finished - started_at).total_seconds(), 3),
            "evidence_finished_at": state.get("provenance_finished_at"),
            "evidence_age_seconds": state.get("evidence_age_seconds"),
            "max_evidence_age_seconds": cfg["max_age_seconds"],
            "max_evidence_age_source": cfg["max_age_source"],
            "default_max_evidence_age_seconds": cfg["default_max_age_seconds"],
            "hard_max_evidence_age_seconds": cfg["hard_max_age_seconds"],
            "timezone": "UTC",
        },
        "provenance": {
            "verifier": "scripts/verify-robotics-registration.sh",
            "core_root": cfg["core_root"],
            "core_src": cfg["core_src"],
            "python_executable": cfg["python_executable"],
            "python_version": cfg["python_version"],
            "scratch_root": cfg["scratch"],
            "result_dir": cfg["result_dir"],
            "evidence_provenance": state.get("evidence_provenance", {}),
        },
        "input": state.get("input", {}),
        "evidence": {
            "source_hashes": state.get("source_hashes", {}),
            "copies": state.get("copies", {}),
            "evidence_dir": os.path.join(cfg["result_dir"], "evidence"),
        },
        "lower": state.get("lower", {}),
        "plan_contract": {
            "contract_version": PLAN_CONTRACT,
            "source": (
                "read from the derived lower repository, not defined by this verifier"),
            "relative_path": PLAN_SCHEMA_RELPATH,
            "schema": state.get("plan_contract"),
        },
        "wheel": {
            "filename": cfg["wheel_filename"],
            "version": DISTRIBUTION_VERSION,
            "sha256": (sha256_file(wheel_path) if os.path.isfile(wheel_path) else None),
            "path": wheel_path,
            "build_command": cfg["build_command"],
            "build_source": cfg["build_source"],
            "build_source_is_scratch_copy": True,
            "build_used_isolation": False,
            "source_repository_mutated": False,
            "install_command": cfg["install_command"],
            "install_target": cfg["target"],
            "install_offline_no_index": True,
            "install_no_deps": True,
        },
        "import_origins": state.get("import_origins", {}),
        "registration": state.get("registration", {}),
        "device_binding": {
            "synthetic_device_id": DEVICE_ID,
            "context": dict(CONTEXT),
            "binding_is_synthetic": True,
            "no_real_resource_was_reserved": True,
            "resource_id_source": "invented by this verifier; it names no real robot",
        },
        "executions": state.get("executions", {}),
        "discovery_errors": state.get("discovery_errors", []),
        "failures": list(failures),
    }

    report["invariants"] = {
        key: (key not in invariant_failures) for key in INVARIANTS
    }
    report["invariant_failures"] = {
        key: list(messages) for key, messages in sorted(invariant_failures.items())
    }
    # An unattributed failure still invalidates the run, even when every named
    # invariant survived it. Say so instead of letting the table imply success.
    report["unattributed_failures"] = [
        message for message in failures
        if not any(message in messages for messages in invariant_failures.values())
    ]

    report_path = os.path.join(cfg["result_dir"], "report.json")
    report_sha = write_atomic_json(report_path, report)

    sys.stdout.write("report_path=%s\n" % report_path)
    sys.stdout.write("report_sha256=%s\n" % report_sha)
    sys.stdout.write("passed=%s\n" % ("true" if passed else "false"))
    if not passed:
        sys.stderr.write("\nrobotics registration verification FAILED:\n")
        for message in failures:
            sys.stderr.write("  - %s\n" % message)
    return 0 if passed else 1


# ==============================================================================
# Main
# ==============================================================================
def main(argv):
    if len(argv) != 2:
        sys.stderr.write("usage: verify_registration.py <config.json>\n")
        return 2

    with open(argv[1], "rb") as handle:
        cfg = json.loads(handle.read().decode("utf-8"))

    install_non_actuation_guards()

    started_at = _dt.datetime.now(_dt.timezone.utc)
    state = {}

    run_dir = cfg["run_dir"]
    run_id = cfg["run_id"]
    modules_repo = cfg["modules_repo"]
    target = os.path.realpath(cfg["target"])
    core_src = os.path.realpath(cfg["core_src"])
    result_dir = cfg["result_dir"]
    evidence_dir = os.path.join(result_dir, "evidence")
    max_age = cfg["max_age_seconds"]

    require(os.path.basename(run_dir) == run_id,
            "run directory basename %r does not match the run id %r"
            % (os.path.basename(run_dir), run_id),
            "run_dir_resolved_and_contained")
    require(run_dir.startswith(os.path.normpath(modules_repo) + os.sep),
            "run directory %s is not contained in the modules repository %s"
            % (run_dir, modules_repo),
            "run_dir_resolved_and_contained")
    require(os.path.realpath(result_dir).startswith(
                os.path.join(os.path.realpath(cfg["core_root"]),
                             "test-results", "robotics-registration") + os.sep),
            "result directory %s is not inside this Core checkout's "
            "test-results/robotics-registration" % result_dir,
            "run_dir_resolved_and_contained")

    # --------------------------------------------------------------------------
    # 1. Upper evidence
    # --------------------------------------------------------------------------
    upper_report_file = read_regular_file(
        "upper report", os.path.join(run_dir, "report.json"), run_dir,
        "upper_report_contract_and_pass_facts")
    upper_cleanup_file = read_regular_file(
        "upper cleanup", os.path.join(run_dir, "cleanup.json"), run_dir,
        "upper_cleanup_contract_run_id_and_final_status")
    lower_evidence_file = read_regular_file(
        "lower evidence", os.path.join(run_dir, "lower-evidence.json"), run_dir,
        "lower_evidence_equals_report_lower_layer")

    if not (upper_report_file and upper_cleanup_file and lower_evidence_file):
        return build_report(cfg, started_at, state)

    upper_report = parse_json("upper report", upper_report_file["bytes"],
                              "upper_report_contract_and_pass_facts")
    upper_cleanup = parse_json("upper cleanup", upper_cleanup_file["bytes"],
                               "upper_cleanup_contract_run_id_and_final_status")
    lower_evidence = parse_json("lower evidence", lower_evidence_file["bytes"],
                                "lower_evidence_equals_report_lower_layer")
    if not all(isinstance(doc, dict)
               for doc in (upper_report, upper_cleanup, lower_evidence)):
        fail("one or more evidence documents are not JSON objects")
        return build_report(cfg, started_at, state)

    inv_upper = "upper_report_contract_and_pass_facts"
    require_exact("upper report contract_version",
                  upper_report.get("contract_version"), UPPER_REPORT_CONTRACT, inv_upper)
    require_true("upper report passed", upper_report.get("passed"), inv_upper)
    require_exact("upper report run_id", upper_report.get("run_id"), run_id, inv_upper)

    provenance = upper_report.get("provenance")
    require(isinstance(provenance, dict), "upper report has no provenance object", inv_upper)
    provenance = provenance if isinstance(provenance, dict) else {}
    finished_at = parse_utc("upper report provenance.finished_at",
                            provenance.get("finished_at"),
                            "evidence_not_future_and_within_max_age")
    evidence_started_at = parse_utc("upper report provenance.started_at",
                                    provenance.get("started_at"),
                                    "evidence_not_future_and_within_max_age")
    if finished_at and evidence_started_at:
        require(evidence_started_at <= finished_at,
                "upper report provenance: started_at is after finished_at",
                "evidence_not_future_and_within_max_age")

    upper_invariants = upper_report.get("invariants")
    if require(isinstance(upper_invariants, dict),
               "upper report has no invariants object", inv_upper):
        for key in sorted(upper_invariants):
            require_true("upper report invariant %r" % key, upper_invariants[key], inv_upper)
        for needed in ("lower_layer_verified", "final_step_is_safe_stop",
                       "gateway_terminal_success", "gateway_did_not_time_out",
                       "physics_gate_satisfied", "displacement_in_window",
                       "stopped_pose_is_stable"):
            require(needed in upper_invariants,
                    "upper report invariants are missing %r" % needed, inv_upper)

    gateway = upper_report.get("gateway_session")
    if require(isinstance(gateway, dict), "upper report has no gateway_session", inv_upper):
        require_false("upper report gateway_session.timed_out",
                      gateway.get("timed_out"), inv_upper)
        require_exact("upper report gateway_session.error",
                      gateway.get("error"), None, inv_upper)
        terminal = gateway.get("terminal_success_states")
        require(isinstance(terminal, list) and gateway.get("state") in terminal,
                "upper report gateway_session.state %r is not a declared terminal "
                "success state" % (gateway.get("state"),), inv_upper)

    step = upper_report.get("step")
    if require(isinstance(step, dict), "upper report has no step object", inv_upper):
        require_exact("upper report step.final_step_capability",
                      step.get("final_step_capability"), SAFE_STOP, inv_upper)
        require_exact("upper report step.request_contract_version",
                      step.get("request_contract_version"), REQUEST_CONTRACT, inv_upper)
        require_exact("upper report step.plan_contract_version",
                      step.get("plan_contract_version"), PLAN_CONTRACT, inv_upper)

    inv_cleanup = "upper_cleanup_contract_run_id_and_final_status"
    inv_restore = "upper_restoration_and_quiescence_facts"
    require_exact("upper cleanup contract_version",
                  upper_cleanup.get("contract_version"), UPPER_CLEANUP_CONTRACT, inv_cleanup)
    require_exact("upper cleanup run_id", upper_cleanup.get("run_id"), run_id, inv_cleanup)
    require_exact("upper cleanup incoming_status",
                  upper_cleanup.get("incoming_status"), 0, inv_cleanup)
    require_exact("upper cleanup final_status",
                  upper_cleanup.get("final_status"), 0, inv_cleanup)
    require_true("upper cleanup restoration_attempted",
                 upper_cleanup.get("restoration_attempted"), inv_restore)
    require_exact("upper cleanup restoration_exit_code",
                  upper_cleanup.get("restoration_exit_code"), 0, inv_restore)
    require_false("upper cleanup restoration_timed_out",
                  upper_cleanup.get("restoration_timed_out"), inv_restore)
    require_true("upper cleanup restored_normal_gateway_runtime",
                 upper_cleanup.get("restored_normal_gateway_runtime"), inv_restore)
    require_true("upper cleanup lower_processes_quiesced",
                 upper_cleanup.get("lower_processes_quiesced"), inv_restore)
    require_true("upper cleanup guest_scratch_removed",
                 upper_cleanup.get("guest_scratch_removed"), inv_restore)

    # --------------------------------------------------------------------------
    # 2. lower-evidence.json is the report's own lower_layer, restated
    # --------------------------------------------------------------------------
    require("contract_version" not in lower_evidence,
            "lower-evidence.json carries a contract_version; by contract it must not",
            "lower_evidence_has_no_contract_version")

    lower_layer = upper_report.get("lower_layer")
    require(isinstance(lower_layer, dict), "upper report has no lower_layer object",
            "lower_evidence_equals_report_lower_layer")
    lower_layer = lower_layer if isinstance(lower_layer, dict) else {}
    require(lower_evidence == lower_layer,
            "lower-evidence.json is not exactly equal to the upper report's lower_layer",
            "lower_evidence_equals_report_lower_layer")

    inv_lower_report = "lower_report_contract_and_pass_facts"
    inv_lower_cleanup = "lower_cleanup_contract_zero_command_and_status"
    require_true("lower_layer.passed", lower_layer.get("passed"), inv_lower_report)
    require_true("lower_layer.report_passed", lower_layer.get("report_passed"),
                 inv_lower_report)
    require_exact("lower_layer.report_contract_version",
                  lower_layer.get("report_contract_version"),
                  LOWER_REPORT_CONTRACT, inv_lower_report)
    require_exact("lower_layer.cleanup_contract_version",
                  lower_layer.get("cleanup_contract_version"),
                  LOWER_CLEANUP_CONTRACT, inv_lower_cleanup)
    require_true("lower_layer.cleanup_has_no_run_id_field_by_contract",
                 lower_layer.get("cleanup_has_no_run_id_field_by_contract"),
                 inv_lower_cleanup)

    checked = lower_layer.get("cleanup_checked")
    if require(isinstance(checked, dict), "lower_layer has no cleanup_checked object",
               inv_lower_cleanup):
        require_true("lower_layer.cleanup_checked.passed", checked.get("passed"),
                     inv_lower_cleanup)
        require_true("lower_layer.cleanup_checked.restored_normal_gateway_runtime",
                     checked.get("restored_normal_gateway_runtime"), inv_lower_cleanup)
        require_true("lower_layer.cleanup_checked.zero_command_published",
                     checked.get("zero_command_published"), inv_lower_cleanup)
        require_exact("lower_layer.cleanup_checked.normal_runtime_restoration_exit_code",
                      checked.get("normal_runtime_restoration_exit_code"), 0,
                      inv_lower_cleanup)
        require_exact("lower_layer.cleanup_checked.verification_status",
                      checked.get("verification_status"), 0, inv_lower_cleanup)

    lower_run_id = lower_layer.get("lower_run_id")
    require_exact("upper cleanup lower_run_id", upper_cleanup.get("lower_run_id"),
                  lower_run_id, inv_cleanup)
    require(isinstance(lower_run_id, str) and lower_run_id == run_id + "-lower",
            "lower_run_id %r is not the upper run id with a -lower suffix"
            % (lower_run_id,), inv_cleanup)

    # --------------------------------------------------------------------------
    # 3. Lower evidence files, in the lower repository
    # --------------------------------------------------------------------------
    inv_paths = "lower_paths_contained_and_regular_files"
    inv_hashes = "declared_sha256_recomputed_and_matched"
    lower_run_dir = lower_layer.get("lower_run_dir")
    lower_report_path = lower_layer.get("report_path")
    lower_cleanup_path = lower_layer.get("cleanup_path")
    lower_repo = None
    lower_report_file = None
    lower_cleanup_file = None

    if not all(isinstance(value, str) and os.path.isabs(value)
               for value in (lower_run_dir, lower_report_path, lower_cleanup_path)):
        fail("lower_layer does not carry absolute lower_run_dir/report_path/cleanup_path",
             inv_paths)
    else:
        lower_run_dir = os.path.normpath(lower_run_dir)
        require(os.path.basename(lower_run_dir) == lower_run_id,
                "lower_run_dir basename %r does not match lower_run_id %r"
                % (os.path.basename(lower_run_dir), lower_run_id), inv_paths)
        parent = os.path.dirname(lower_run_dir)
        require(os.path.basename(parent) == LOWER_RESULTS_PARENT,
                "lower_run_dir is not under results/%s: %s"
                % (LOWER_RESULTS_PARENT, lower_run_dir), inv_paths)
        results_parent = os.path.dirname(parent)
        require(os.path.basename(results_parent) == "results",
                "lower_run_dir is not under a results/ directory: %s" % lower_run_dir,
                inv_paths)
        lower_repo = os.path.dirname(results_parent)
        require(lower_repo != os.path.normpath(modules_repo),
                "the lower repository and the modules repository are the same tree: %s"
                % lower_repo, inv_paths)
        require(os.path.isdir(lower_run_dir) and not os.path.islink(lower_run_dir),
                "lower run directory is missing or a symlink: %s" % lower_run_dir,
                inv_paths)
        lower_report_file = read_regular_file(
            "lower report", lower_report_path, lower_run_dir, inv_paths)
        lower_cleanup_file = read_regular_file(
            "lower cleanup", lower_cleanup_path, lower_run_dir, inv_paths)

    # The plan contract belongs to the lower repository, so it is only loadable
    # once the evidence has told us which repository that is.
    inv_contract = "plan_contract_schema_is_the_canonical_lower_contract"
    plan_schema = None
    plan_contract_facts = None
    if lower_repo is None:
        fail("the lower repository could not be derived, so the canonical %s schema "
             "could not be read" % PLAN_CONTRACT, inv_contract)
    else:
        plan_schema, plan_contract_facts = load_plan_contract(lower_repo, inv_contract)

    lower_report = None
    lower_cleanup = None
    if lower_report_file:
        require_exact("lower report sha256 (recomputed against the declared digest)",
                      lower_report_file["sha256"], lower_layer.get("report_sha256"),
                      inv_hashes)
        lower_report = parse_json("lower report", lower_report_file["bytes"],
                                  inv_lower_report)
    if lower_cleanup_file:
        require_exact("lower cleanup sha256 (recomputed against the declared digest)",
                      lower_cleanup_file["sha256"], lower_layer.get("cleanup_sha256"),
                      inv_hashes)
        lower_cleanup = parse_json("lower cleanup", lower_cleanup_file["bytes"],
                                   inv_lower_cleanup)

    if isinstance(lower_report, dict):
        require_exact("lower report contract_version",
                      lower_report.get("contract_version"), LOWER_REPORT_CONTRACT,
                      inv_lower_report)
        require_true("lower report passed", lower_report.get("passed"), inv_lower_report)
        robot = lower_report.get("robot")
        if require(isinstance(robot, dict), "lower report has no robot object",
                   inv_lower_report):
            require_true("lower report robot.passed", robot.get("passed"),
                         inv_lower_report)
            require_exact("lower report robot.contract_version",
                          robot.get("contract_version"), LOWER_REPORT_CONTRACT,
                          inv_lower_report)
        fault = lower_report.get("fault_safety")
        if require(isinstance(fault, dict), "lower report has no fault_safety object",
                   inv_lower_report):
            require_true("lower report fault_safety.passed", fault.get("passed"),
                         inv_lower_report)
            require_true("lower report fault_safety.safety_latched",
                         fault.get("safety_latched"), inv_lower_report)

    if isinstance(lower_cleanup, dict):
        require_exact("lower cleanup contract_version",
                      lower_cleanup.get("contract_version"), LOWER_CLEANUP_CONTRACT,
                      inv_lower_cleanup)
        require("run_id" not in lower_cleanup,
                "lower cleanup carries a run_id; the lower cleanup contract has none",
                inv_lower_cleanup)
        require_true("lower cleanup passed", lower_cleanup.get("passed"),
                     inv_lower_cleanup)
        require_true("lower cleanup restored_normal_gateway_runtime",
                     lower_cleanup.get("restored_normal_gateway_runtime"),
                     inv_lower_cleanup)
        require_true("lower cleanup zero_command_published",
                     lower_cleanup.get("zero_command_published"), inv_lower_cleanup)
        require_exact("lower cleanup normal_runtime_restoration_exit_code",
                      lower_cleanup.get("normal_runtime_restoration_exit_code"), 0,
                      inv_lower_cleanup)
        require_exact("lower cleanup verification_status",
                      lower_cleanup.get("verification_status"), 0, inv_lower_cleanup)
        if isinstance(checked, dict):
            restated = dict((key, lower_cleanup.get(key)) for key in checked)
            require(restated == checked,
                    "lower_layer.cleanup_checked does not restate the lower cleanup file",
                    inv_lower_cleanup)

    # --------------------------------------------------------------------------
    # 4. Freshness - not future, not stale
    # --------------------------------------------------------------------------
    inv_fresh = "evidence_not_future_and_within_max_age"
    now = _dt.datetime.now(_dt.timezone.utc)
    evidence_age = None
    if finished_at is not None:
        evidence_age = (now - finished_at).total_seconds()
        require(evidence_age >= 0,
                "evidence finished_at %s is in the future relative to %s"
                % (finished_at.isoformat(), now.isoformat()), inv_fresh)
        require(evidence_age <= max_age,
                "evidence is %.3fs old, older than the %ds maximum in force"
                % (evidence_age, max_age), inv_fresh)

    evidence_files = {
        "upper-report.json": upper_report_file,
        "upper-cleanup.json": upper_cleanup_file,
        "lower-evidence.json": lower_evidence_file,
        "lower-report.json": lower_report_file,
        "lower-cleanup.json": lower_cleanup_file,
    }
    now_epoch = now.timestamp()
    for name in sorted(evidence_files):
        entry = evidence_files[name]
        if entry is None:
            fail("evidence file %s was not readable" % name, inv_paths)
            continue
        if entry["mtime"] > now_epoch + 1.0:
            fail("evidence file %s has a future mtime: %s" % (name, entry["path"]),
                 inv_fresh)

    # --------------------------------------------------------------------------
    # 5. Copy all five evidence files into the durable Core result
    # --------------------------------------------------------------------------
    inv_copy = "five_evidence_files_copied_with_matching_hashes"
    copies = {}
    if all(evidence_files[name] is not None for name in evidence_files):
        for name in sorted(evidence_files):
            entry = evidence_files[name]
            destination = os.path.join(evidence_dir, name)
            with open(destination, "wb") as handle:
                handle.write(entry["bytes"])
                handle.flush()
                os.fsync(handle.fileno())
            copy_hash = sha256_file(destination)
            require_exact("evidence copy %s sha256" % name, copy_hash,
                          entry["sha256"], inv_copy)
            copies[name] = {
                "source_path": entry["path"],
                "source_sha256": entry["sha256"],
                "source_size_bytes": entry["size"],
                "copy_path": destination,
                "copy_sha256": copy_hash,
            }
        require(len(copies) == 5,
                "expected five copied evidence files, got %d" % len(copies), inv_copy)
    else:
        fail("not all five evidence files were readable; nothing was copied", inv_copy)

    state["copies"] = copies
    state["source_hashes"] = dict(
        (name, evidence_files[name]["sha256"])
        for name in sorted(evidence_files) if evidence_files[name] is not None)
    state["provenance_finished_at"] = provenance.get("finished_at")
    state["evidence_age_seconds"] = (
        round(evidence_age, 3) if evidence_age is not None else None)
    state["evidence_provenance"] = {
        "started_at": provenance.get("started_at"),
        "finished_at": provenance.get("finished_at"),
        "host_platform": provenance.get("host_platform"),
        "repo_commit": provenance.get("repo_commit"),
        "lower_repo_commit": provenance.get("lower_repo_commit"),
        "verifier_sha256": provenance.get("verifier_sha256"),
        "verifier_behavior_revision": provenance.get("verifier_behavior_revision"),
    }
    state["input"] = {
        "run_dir": run_dir,
        "run_dir_input": cfg["run_dir_input"],
        "run_dir_input_kind": cfg["run_dir_input_kind"],
        "run_id": run_id,
        "modules_repo": modules_repo,
        "lower_repo": lower_repo,
        "core_root": cfg["core_root"],
        "max_evidence_age_seconds": max_age,
        "max_evidence_age_source": cfg["max_age_source"],
    }
    state["lower"] = {
        "lower_run_id": lower_run_id,
        "lower_run_dir": lower_run_dir,
        "report": {
            "path": lower_report_path,
            "contract_version": LOWER_REPORT_CONTRACT,
            "declared_sha256": lower_layer.get("report_sha256"),
            "recomputed_sha256": (
                lower_report_file["sha256"] if lower_report_file else None),
        },
        "cleanup": {
            "path": lower_cleanup_path,
            "contract_version": LOWER_CLEANUP_CONTRACT,
            "declared_sha256": lower_layer.get("cleanup_sha256"),
            "recomputed_sha256": (
                lower_cleanup_file["sha256"] if lower_cleanup_file else None),
        },
        "cleanup_checked": checked if isinstance(checked, dict) else None,
    }
    state["plan_contract"] = plan_contract_facts

    # --------------------------------------------------------------------------
    # 6. Registration through the real public ModuleRegistry surface
    # --------------------------------------------------------------------------
    sys.path.insert(0, core_src)
    sys.path.insert(0, target)

    inv_ep = "exactly_one_robotics_entry_point"
    inv_dist = "robotics_distribution_identity_inside_target"
    inv_plugin = "robotics_plugin_loaded_without_discovery_error"
    inv_owned = "owned_module_ids_exactly_move_stop_turn"
    inv_origin = "import_origins_are_target_then_core_src"

    entry_points_seen = []
    discovery_errors = []
    executions = {}
    selected = {}

    from importlib.metadata import distributions

    seen_keys = set()
    for dist in distributions():
        try:
            dist_name = dist.metadata["Name"]
            dist_version = dist.version
            dist_location = os.path.realpath(str(dist.locate_file("")))
        except Exception:
            continue
        try:
            dist_entry_points = list(dist.entry_points or [])
        except Exception:
            continue
        for entry_point in dist_entry_points:
            if getattr(entry_point, "group", None) != ENTRY_POINT_GROUP:
                continue
            key = (dist_location, dist_name, entry_point.name, entry_point.value)
            if key in seen_keys:
                continue
            seen_keys.add(key)
            entry_points_seen.append({
                "group": ENTRY_POINT_GROUP,
                "name": entry_point.name,
                "value": entry_point.value,
                "distribution": dist_name,
                "distribution_version": dist_version,
                "distribution_location": dist_location,
            })
    entry_points_seen.sort(key=lambda item: (item["name"], str(item["distribution"]),
                                             item["distribution_location"]))

    # flyto-core legitimately ships its own `community` entry point, and any
    # other installed plugin is somebody else's correct business. The
    # requirement is that exactly one entry point is the robotics one - not that
    # robotics is alone in the group. Everything else is preserved and reported.
    robotics_eps = [ep for ep in entry_points_seen if ep["name"] == ENTRY_POINT_NAME]
    other_eps = [ep for ep in entry_points_seen if ep["name"] != ENTRY_POINT_NAME]

    if require(len(robotics_eps) == 1,
               "expected exactly one %r entry point in group %s, found %d"
               % (ENTRY_POINT_NAME, ENTRY_POINT_GROUP, len(robotics_eps)), inv_ep):
        selected = dict(robotics_eps[0])
        require_exact("robotics entry point value", selected["value"],
                      ENTRY_POINT_VALUE, inv_ep)
        normalised = str(selected["distribution"] or "").strip().lower().replace("_", "-")
        require_exact("robotics distribution name", normalised, DISTRIBUTION_NAME, inv_dist)
        require_exact("robotics distribution version",
                      selected["distribution_version"], DISTRIBUTION_VERSION, inv_dist)
        require_exact("robotics distribution metadata location",
                      selected["distribution_location"], target, inv_dist)

    from core.modules import ModuleRegistry

    registry_logger = logging.getLogger("core.modules.registry.core")

    class _ErrorCollector(logging.Handler):
        def emit(self, record):
            if record.levelno >= logging.ERROR:
                discovery_errors.append(record.getMessage())

    collector = _ErrorCollector(level=logging.ERROR)
    previous_level = registry_logger.level
    registry_logger.addHandler(collector)
    registry_logger.setLevel(logging.ERROR)
    try:
        ModuleRegistry.clear()
        ModuleRegistry.discover_plugins(force=True)
    finally:
        registry_logger.removeHandler(collector)
        registry_logger.setLevel(previous_level)

    for message in discovery_errors:
        if ENTRY_POINT_NAME in message:
            fail("plugin discovery reported an error for the robotics plugin: %s"
                 % message, inv_plugin)

    plugins = ModuleRegistry.get_plugins()
    plugins_reported = {}
    for name in sorted(plugins):
        info = plugins[name]
        plugins_reported[name] = {
            "version": getattr(info, "version", None),
            "module_count": getattr(info, "module_count", None),
            "entry_point": getattr(info, "entry_point", None),
        }

    owned_module_ids = []
    if require(ENTRY_POINT_NAME in plugins,
               "the robotics plugin did not load; discovered plugins: %s"
               % (sorted(plugins),), inv_plugin):
        info = plugins[ENTRY_POINT_NAME]
        require_exact("robotics plugin version", getattr(info, "version", None),
                      DISTRIBUTION_VERSION, inv_plugin)
        require_exact("robotics plugin entry point", getattr(info, "entry_point", None),
                      ENTRY_POINT_VALUE, inv_plugin)
        require_exact("robotics plugin module_count",
                      getattr(info, "module_count", None), len(EXPECTED_MODULE_IDS),
                      inv_owned)
        owned_module_ids = sorted(ModuleRegistry.get_plugin_modules(ENTRY_POINT_NAME))
        require_exact("robotics owned module ids", owned_module_ids,
                      EXPECTED_MODULE_IDS, inv_owned)

    import flyto_modules_robotics as robotics_package
    import core as core_package
    import_origins = {
        "flyto_modules_robotics": os.path.realpath(robotics_package.__file__ or ""),
        "core": os.path.realpath(core_package.__file__ or ""),
        "sys_path_head": list(sys.path[:2]),
    }
    require(import_origins["flyto_modules_robotics"].startswith(target + os.sep),
            "flyto_modules_robotics was imported from outside the install target: %s"
            % import_origins["flyto_modules_robotics"], inv_origin)
    require(import_origins["core"].startswith(core_src + os.sep),
            "core was imported from outside this checkout: %s"
            % import_origins["core"], inv_origin)
    require(sys.path[0] == target and sys.path[1] == core_src,
            "sys.path does not put the install target first and this Core src second: %s"
            % (sys.path[:2],), inv_origin)

    state["import_origins"] = import_origins
    state["discovery_errors"] = list(discovery_errors)
    state["registration"] = {
        "entry_point_group": ENTRY_POINT_GROUP,
        "entry_points_in_group": entry_points_seen,
        "other_entry_points_preserved": other_eps,
        "selected_entry_point": selected,
        "plugins": plugins_reported,
        "discovery_errors": list(discovery_errors),
        "owned_module_ids": owned_module_ids,
        "registry_api_used": [
            "ModuleRegistry.clear",
            "ModuleRegistry.discover_plugins",
            "ModuleRegistry.get_plugins",
            "ModuleRegistry.get_plugin_modules",
            "ModuleRegistry.execute",
        ],
        "modules_were_never_instantiated_directly": True,
    }

    # --------------------------------------------------------------------------
    # 7. Declaration-only execution of each owned module
    # --------------------------------------------------------------------------
    if owned_module_ids == EXPECTED_MODULE_IDS:
        for module_id in EXPECTED_MODULE_IDS:
            params = dict(MODULE_PARAMS[module_id])
            context = dict(CONTEXT)
            try:
                result = asyncio.run(ModuleRegistry.execute(module_id, params, context))
            except NonActuatingViolation as exc:
                fail("%s attempted to act on the world: %s" % (module_id, exc),
                     "declarations_are_not_dispatched")
                continue
            except Exception as exc:
                fail("%s raised during declaration-only execution: %r"
                     % (module_id, exc), "declarations_are_not_dispatched")
                continue
            require_exact("%s: execution context after the call" % module_id,
                          context, {"resource_id": DEVICE_ID},
                          "execution_context_unchanged")
            executions[module_id] = inspect_declaration(module_id, params, result,
                                                        plan_schema)

    state["executions"] = executions
    return build_report(cfg, started_at, state)


if __name__ == "__main__":
    sys.exit(main(sys.argv))
PYEOF

note "verifying registration and declarations (no dispatch, no devices, no network)"
VERIFY_OUT="$SCRATCH/verify.out"
set +e
"$PYTHON_BIN" "$VERIFIER" "$CONFIG" | tee "$VERIFY_OUT"
VERIFY_STATUS=${PIPESTATUS[0]}
set -e

REPORT_PATH="$RESULT_DIR/report.json"
[ -f "$REPORT_PATH" ] || die "the embedded verifier did not produce $REPORT_PATH"

REPORT_SHA="$(sed -n 's/^report_sha256=//p' "$VERIFY_OUT" | tail -n 1)"

if [ "$VERIFY_STATUS" -ne 0 ]; then
    printf '%s: FAILED\n' "$PROG" >&2
    printf '  report:  %s\n' "$REPORT_PATH" >&2
    printf '  sha256:  %s\n' "$REPORT_SHA" >&2
    exit "$VERIFY_STATUS"
fi

printf '%s: PASSED\n' "$PROG"
printf '  report:  %s\n' "$REPORT_PATH"
printf '  sha256:  %s\n' "$REPORT_SHA"
exit 0
