# Copyright 2026 Flyto2. Licensed under Apache-2.0. See LICENSE.

"""
Git Diff Module
Get git diff output with statistics

HOW FAR THIS MODULE FOLLOWS REALITY

`git.diff` is the odd one in the git group: it is side-effecting by category and
changes nothing. Its "effect" is the reading, so the question the ladder asks
becomes "is the answer in the payload, or only the report that an answer was
produced" -- which is the same question `dns.lookup` answers and gets the same
two rungs.

    diff text or a numstat line came back           OBSERVED
        `diff` holds bytes git generated by walking real trees, and
        `files_changed` counts tab-separated numstat records that came from the
        same walk. Both are content, not status.

    git exited 0 with nothing to say                ACCEPTED
        An empty diff is the honest floor and not a disappointment. `diff == ''`
        with `files_changed == 0` is byte-identical to what a module that never
        ran would return, so it cannot be evidence that anything was examined.
        What is known is that git took the request and answered, and that is
        what ACCEPTED means. A consumer wanting "there are definitely no
        changes" is asking for a rung this code does not reach.

    not a repo / git refused / git missing          FAILED
        Definite. No answer was produced and none is coming.

Every error path is FAILED and none is INDETERMINATE, which is the opposite of
`git.commit` and `git.clone` in this same package -- deliberately. Those two
write, so an exception mid-flight leaves a question about the world. This one
reads: when it raises, nothing happened to the repository and the only casualty
is the answer. There is nothing to be uncertain about.

A second git invocation produces the counts (`--numstat`), and it can fail on
its own while the first succeeded. That is recorded as `numstat_available`
rather than smoothed into a zero, for the reason `git.commit` records
`diffstat_available`: a count of 0 and a count that was never taken are
different facts, and one integer cannot hold both.
"""

import asyncio
import logging
import os
from typing import Any, Dict, List

from ....engine.outcome import ClaimBy, Outcome, envelope
from ....utils import validate_path_with_env_config
from ...registry import register_module
from ...schema import compose
from ...schema.builders import field
from ...schema.constants import FieldGroup


logger = logging.getLogger(__name__)


async def _run_git(repo_path: str, *args: str) -> tuple:
    """Run a git command in the given repo and return (returncode, stdout, stderr)."""
    proc = await asyncio.create_subprocess_exec(
        'git', '-C', repo_path, *args,
        stdout=asyncio.subprocess.PIPE,
        stderr=asyncio.subprocess.PIPE,
    )
    out, err = await proc.communicate()
    return proc.returncode, out.decode('utf-8', errors='replace'), err.decode('utf-8', errors='replace')


def _build_diff_args(staged: bool, ref1: str, ref2: str = None, extra_flags: List[str] = None) -> List[str]:
    """Build git diff argument list."""
    args: List[str] = ['diff']
    if staged:
        args.append('--cached')
    elif ref2:
        args.extend([ref1, ref2])
    else:
        args.append(ref1)
    if extra_flags:
        args.extend(extra_flags)
    return args


def _parse_numstat(numstat_out: str) -> tuple:
    """Parse git diff --numstat output into (files_changed, insertions, deletions)."""
    files_changed = 0
    insertions = 0
    deletions = 0
    if not numstat_out.strip():
        return files_changed, insertions, deletions
    for line in numstat_out.strip().split('\n'):
        parts = line.split('\t')
        if len(parts) >= 3:
            files_changed += 1
            try:
                insertions += int(parts[0])
            except ValueError:
                pass
            try:
                deletions += int(parts[1])
            except ValueError:
                pass
    return files_changed, insertions, deletions


def _refused(kind: str, detail: str, **fields: Any) -> Dict[str, Any]:
    """The envelope for a path that produced no diff.

    FAILED on every one. See the module docstring for why none of them is
    INDETERMINATE: a read that raises leaves no question about the world.
    """
    return envelope(
        Outcome.FAILED,
        claim_by=ClaimBy.NONE,
        effects=[dict({'kind': kind, 'measured_by': None, 'detail': detail}, **fields)],
    )


def _diff_outcome(
    *,
    repo_path: str,
    diff_out: str,
    files_changed: int,
    insertions: int,
    deletions: int,
    numstat_available: bool,
) -> Dict[str, Any]:
    """The rung this read earned; the decision is whether anything came back.

    `diff_out` is checked before `files_changed` because it is the payload the
    caller asked for and it is non-empty in cases numstat reports nothing --
    a pure mode change, for instance, has a diff header and no line counts.
    Either one being non-empty means git produced content describing the trees
    it walked.
    """
    if diff_out or files_changed:
        return envelope(
            Outcome.OBSERVED,
            claim_by=ClaimBy.NONE,
            effects=[{
                'kind': 'git_diff_returned',
                'repo_path': repo_path,
                'diff_characters': len(diff_out),
                'files_changed': files_changed,
                'insertions': insertions,
                'deletions': deletions,
                'numstat_available': numstat_available,
                'measured_by': (
                    'git diff output, with counts from a second git diff '
                    '--numstat over the same refs'
                ),
                'detail': (
                    'Content git generated from the trees named by the refs. An '
                    'observation of the repository as it is now, not a claim '
                    'that it will still say this a moment from now.'
                ),
            }],
        )

    return envelope(
        Outcome.ACCEPTED,
        claim_by=ClaimBy.NONE,
        effects=[{
            'kind': 'git_diff_empty',
            'repo_path': repo_path,
            'numstat_available': numstat_available,
            'measured_by': None,
            'detail': (
                'git exited 0 and produced no diff and no counts. That the '
                'command was taken and answered is all this says: an empty '
                'diff string reads identically whether the trees match, the '
                'pathspec matched nothing, or nothing was ever asked.'
            ),
        }],
    )


@register_module(
    module_id='git.diff',
    version='1.0.0',
    category='atomic',
    subcategory='git',
    tags=['git', 'diff', 'changes', 'devops'],
    label='Git Diff',
    label_key='modules.git.diff.label',
    description='Get git diff',
    description_key='modules.git.diff.description',
    icon='GitPullRequest',
    color='#F05032',

    input_types=['string', 'object'],
    output_types=['object'],
    can_connect_to=['*'],
    can_receive_from=['*'],

    timeout_ms=60000,
    retryable=True,
    max_retries=1,
    concurrent_safe=True,

    requires_credentials=False,
    handles_sensitive_data=False,
    required_permissions=['filesystem.read'],

    params_schema=compose(
        field('repo_path', type='string', label='Repository Path', label_key='modules.git.diff.params.repo_path.label',
              description='Path to git repository', required=True,
              placeholder='/home/user/project', group=FieldGroup.BASIC),
        field('ref1', type='string', label='Reference 1', label_key='modules.git.diff.params.ref1.label',
              description='First reference (commit, branch, tag)', default='HEAD',
              placeholder='HEAD', group=FieldGroup.OPTIONS),
        field('ref2', type='string', label='Reference 2', label_key='modules.git.diff.params.ref2.label',
              description='Second reference to compare against',
              placeholder='main', group=FieldGroup.OPTIONS),
        field('staged', type='boolean', label='Staged Only', label_key='modules.git.diff.params.staged.label',
              description='Show only staged changes (--cached)', default=False,
              group=FieldGroup.OPTIONS),
        field('stat_only', type='boolean', label='Stats Only', label_key='modules.git.diff.params.stat_only.label',
              description='Show only file statistics (--stat)', default=False,
              group=FieldGroup.OPTIONS),
    ),
    output_schema={
        'ok': {'type': 'boolean', 'description': 'Whether diff succeeded'},
        'data': {
            'type': 'object',
            'properties': {
                'diff': {'type': 'string', 'description': 'Diff output'},
                'files_changed': {
                    'type': 'number',
                    'description': (
                        'Number of files changed. 0 also when the --numstat pass '
                        'failed -- see outcome.effects[].numstat_available'
                    ),
                },
                'insertions': {'type': 'number', 'description': 'Number of line insertions'},
                'deletions': {'type': 'number', 'description': 'Number of line deletions'},
                'outcome': {
                    'type': 'object',
                    'description': (
                        'How far this read was followed: observed when git returned '
                        'diff content or counts, accepted when it answered with '
                        'nothing, failed when no answer was produced'
                    ),
                },
            }
        }
    },
    examples=[
        {
            'title': 'Show unstaged changes',
            'title_key': 'modules.git.diff.examples.unstaged.title',
            'params': {
                'repo_path': '/home/user/project'
            }
        },
        {
            'title': 'Compare branches',
            'title_key': 'modules.git.diff.examples.branches.title',
            'params': {
                'repo_path': '/home/user/project',
                'ref1': 'main',
                'ref2': 'feature/login'
            }
        },
        {
            'title': 'Show staged changes stats',
            'title_key': 'modules.git.diff.examples.staged.title',
            'params': {
                'repo_path': '/home/user/project',
                'staged': True,
                'stat_only': True
            }
        }
    ],
    author='Flyto2 Team',
    license='MIT'
)
async def git_diff(context: Dict[str, Any]) -> Dict[str, Any]:
    """Get git diff"""
    params = context['params']
    # SECURITY: the diff body is returned to the caller, so an unconfined
    # repo_path reads out any git tree on the host — the read side of
    # GHSA-wc94-386q-5478.
    repo_path = validate_path_with_env_config(str(params['repo_path']))
    ref1 = params.get('ref1', 'HEAD')
    ref2 = params.get('ref2')
    staged = params.get('staged', False)
    stat_only = params.get('stat_only', False)

    if not os.path.isdir(os.path.join(repo_path, '.git')):
        return {
            'ok': False,
            'error': f'Not a git repository: {repo_path}',
            'error_code': 'NOT_A_REPO',
            'outcome': _refused(
                'git_repo_absent',
                'No .git directory at this path, so no git process was started.',
                repo_path=repo_path,
            ),
        }

    try:
        diff_args = _build_diff_args(staged, ref1, ref2, ['--stat'] if stat_only else None)
        rc, diff_out, err = await _run_git(repo_path, *diff_args)
        if rc != 0:
            return {
                'ok': False,
                'error': f'git diff failed: {err.strip()}',
                'error_code': 'DIFF_FAILED',
                'outcome': _refused(
                    'git_diff_rejected',
                    'git diff exited non-zero -- an unknown ref or an unreadable '
                    'repository. No diff was produced.',
                    repo_path=repo_path,
                    exit_code=rc,
                ),
            }

        numstat_args = _build_diff_args(staged, ref1, ref2, ['--numstat'])
        rc, numstat_out, _ = await _run_git(repo_path, *numstat_args)
        numstat_available = rc == 0
        files_changed, insertions, deletions = (
            _parse_numstat(numstat_out) if numstat_available else (0, 0, 0)
        )

        logger.info(f"Git diff: {files_changed} files, +{insertions}/-{deletions}")
        return {
            'ok': True,
            'data': {
                'diff': diff_out,
                'files_changed': files_changed,
                'insertions': insertions,
                'deletions': deletions,
                'outcome': _diff_outcome(
                    repo_path=repo_path,
                    diff_out=diff_out,
                    files_changed=files_changed,
                    insertions=insertions,
                    deletions=deletions,
                    numstat_available=numstat_available,
                ),
            },
        }

    except FileNotFoundError:
        return {
            'ok': False,
            'error': 'git command not found. Ensure git is installed.',
            'error_code': 'GIT_NOT_FOUND',
            'outcome': _refused(
                'git_binary_absent',
                'The git executable could not be spawned, so nothing left this process.',
                repo_path=repo_path,
            ),
        }
    except Exception as e:
        logger.error(f"Git diff error: {e}")
        return {
            'ok': False,
            'error': str(e),
            'error_code': 'DIFF_ERROR',
            'outcome': _refused(
                'git_diff_raised',
                'An exception was raised while driving git diff. This module only '
                'reads, so the repository is unchanged and the only thing lost is '
                'the answer -- failed, not indeterminate.',
                repo_path=repo_path,
                error=f'{type(e).__name__}: {e}',
            ),
        }
