# API + LLM + File Workflow Example
# 此 workflow 結合 HTTP API、LLM 分析和文件保存
# Run: python run.py examples/api_llm_file_combo/workflow.yaml

name: API Data Analysis Pipeline
description: |
  使用 HTTP API 獲取數據，LLM 進行分析，然後將結果保存到文件。
  演示 api.* + llm.* + file.* 模組的組合使用。

# 全局變量
variables:
  output_dir: /tmp/flyto_analysis

steps:
  # Step 1: 從公開 API 獲取數據
  - id: fetch_posts
    module: http.request
    params:
      url: "https://jsonplaceholder.typicode.com/posts"
      method: GET
      query:
        _limit: 5
      timeout: 30
    description: 從 JSONPlaceholder API 獲取前 5 篇文章

  # Step 2: 使用 LLM 分析獲取的數據
  - id: analyze_content
    module: llm.chat
    params:
      prompt: |
        請分析以下 API 返回的文章數據，並提供：
        1. 文章主題摘要
        2. 常見關鍵詞
        3. 內容風格分析

        數據內容:
        ${fetch_posts.body}
      system_prompt: |
        你是一個數據分析專家。請用繁體中文回答。
        回答要簡潔、有條理。
      provider: openai
      model: gpt-4o-mini
      temperature: 0.3
      max_tokens: 1000
      response_format: markdown
    description: 使用 LLM 分析文章內容

  # Step 3: 將分析結果保存到文件
  - id: save_report
    module: file.write
    params:
      path: /tmp/flyto_analysis/api_analysis_report.md
      content: |
        # API 數據分析報告

        ## 原始數據來源
        - URL: https://jsonplaceholder.typicode.com/posts
        - 獲取狀態: ${fetch_posts.ok}
        - HTTP 狀態碼: ${fetch_posts.status}

        ## LLM 分析結果

        ${analyze_content.response}

        ---
        *報告由 Flyto Core 自動生成*
      mode: overwrite
      encoding: utf-8
    description: 將分析報告保存為 Markdown 文件

# 輸出配置
outputs:
  report_path: "${save_report.path}"
  api_success: "${fetch_posts.ok}"
  analysis_tokens: "${analyze_content.tokens_used}"
